### ISSUE TITLE
Question privacy feature on_motion_detected stream videoquality -50% and text overlay

### ISSUE THREAD

**Issue by relcead** [Motion-Project/motion#1007]
Hello and thank you for the great project. It is awesome. For a web stream on a golf course using motion project we like to find a easy way to remove pictures of moving objects in the picture. 

Is there a easy way to either set the image quality -50% for the time of motion detected or cut out or overlay the moving objects? 

Is there an easy way to make a text overlay on_motion_detected. "Privacy Mode"

We want to find the best way of giving the people at home the possibility to watch the stream in real time with good quality. When there is people moving in the stream we need to ensure privacy of our customers by removing their picture somehow.

Thank you for any recommends.

**Comment by Mr-DaveDev** [comment]
This may be question better for the user list as described on the [support page](https://motion-project.github.io/motion_support.html).  

You could look at executing scripts to the [webcontrol](https://motion-project.github.io/motion_config.html#OptDetail_Webcontrol) using the [`on_event_start`](https://motion-project.github.io/motion_config.html#on_event_start) and  [`on_event_end`](https://motion-project.github.io/motion_config.html#on_event_end) and then set the [`stream_quality`](https://motion-project.github.io/motion_config.html#stream_quality) between 1 and a high quality setting.  

If you want to try via the code for your project, you could try to pause the stream within webu_stream by looking for whether motion is currently being detected.  You could also hard code the quality within event.c based upon the detection variable or try to black out the section of the image which would require revisions in alg.c.  

I would not anticipate that this functionality would be embedded into the code due to its unique nature.

**Comment by relcead** [comment]
Thank you for your help. We will dive into your suggestions.
