### ISSUE TITLE
INSTALL should refer autopoint and libmicrohttpd-dev as required packages to build

### ISSUE THREAD

**Issue by haarer** [Motion-Project/motion#1042]
0. Reviewed guide and contributing documents? (Yes):
1. version [master  @ 98f060d]: 
2. compiled from git
3. standalone or part of third party [n.a.]: 
4. video stream source [n.a.]: 
5. hardware [cubietruck, armhf]: 
6. operating system [buster]

reproduce: 
clone git
install prerequisites as in motion/doc/INSTALL
autoreconf  -> complains about missing autopoint

```
autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext

```
installing autopoint fixes this
`apt install autopoint `

**Comment by Mr-Dave** [comment]
Thanks for opening a issue but it will be closed since the current instructions included with the master branch git do include these references.  

INSTALL file references these [here](https://github.com/Motion-Project/motion/blob/98f060dacb1efb7f308b9f454777a7c8f53de89b/doc/INSTALL#L11)

Build instructions refer to them [here](https://github.com/Motion-Project/motion/blob/98f060dacb1efb7f308b9f454777a7c8f53de89b/doc/motion_build.html#L184) and [here](https://github.com/Motion-Project/motion/blob/98f060dacb1efb7f308b9f454777a7c8f53de89b/doc/motion_build.html#L255)

**Comment by haarer** [comment]
Thanks, for pointing it out so kindly. It was my fault. 



Am 19. Oktober 2019 19:31:14 MESZ schrieb Mr-Dave <notifications@github.com>:
>Thanks for opening a issue but it will be closed since the current
>instructions included with the master branch git do include these
>references.  
>
>INSTALL file references these
>[here](https://github.com/Motion-Project/motion/blob/98f060dacb1efb7f308b9f454777a7c8f53de89b/doc/INSTALL#L11)
>
>Build instructions refer to them
>[here](https://github.com/Motion-Project/motion/blob/98f060dacb1efb7f308b9f454777a7c8f53de89b/doc/motion_build.html#L184)
>and
>[here](https://github.com/Motion-Project/motion/blob/98f060dacb1efb7f308b9f454777a7c8f53de89b/doc/motion_build.html#L255)
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Motion-Project/motion/issues/1042#issuecomment-544177029

-- 
Gruß,
Alexander
