### ISSUE TITLE
Implement HW decoding for h264_qsv when it is available

### ISSUE THREAD

**Issue by rayzorben** [Motion-Project/motion#1061]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]:  4.2.2+git20191030-d8ea81d
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]:  motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]:  x86_64/nvidia
6. operating system [16.04, Stretch, etc, FreeBSD, other]: arch

I am getting the following warning when using motion. The only thing of note is that I am trying to use nvidia hardware decoding via 
`netcam_decoder h264_cuvid`

This is the warning I am getting
```
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: ******************************************************
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: The image sent is being 
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: trancoded to YUV420P.  If possible change netcam 
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: picture format to YUV420P to possibly lower CPU usage.
[1:ml1] [NTC] [NET] netcam_rtsp_ntc: ******************************************************
```

My goal is to lower CPU usage as much as possible, so this is important to me to resolve.

**Comment by tosiara** [comment]
`netcam_decoder` is not a valid config option. Where did you get it from?

**Comment by rayzorben** [comment]
> `netcam_decoder` is not a valid config option. Where did you get it from?

Uhm, yes it is? https://github.com/Motion-Project/motion/commit/5d88fe68bb97f1df6df2ce05214dff58751c8438

**Comment by rayzorben** [comment]
My goal would be to replicate this command line. When using ffmpeg with these options on a single camera, ffmpeg uses 2% CPU (of 800% CPU - 8 cores @ 100% CPU).

`ffmpeg -rtsp_transport tcp -y -hwaccel cuvid -c:v h264_cuvid -i 'rtsp://user:pass@192.168.0.20/cam/realmonitor?channel=1&subtype=0' -vcodec h264_nvenc out.h264`

When I use motion with the same camera, it uses 30% CPU. When I use it with `netcam_decoder h264_cuvid` it is down to 20% CPU, but still 10x that of just direct ffmpeg. 

But when I use motion with 6 cameras (default settings) it is using 300-400% CPU.

**Comment by tosiara** [comment]
You are referencing code that hasn't been released yet, this new option is less than 1 month old. Maybe @Mr-Dave can answer

**Comment by Mr-DaveDev** [comment]
The output pixel format of the decoder is decided by those creating the decoder or manufacturing the camera.  In this case, it seems that their decision was to provide the output image in a pixel format other than yuv420p.  

Motion requires the format for consistency in processing.  i.e. All images get converted to that format so that all the code works consistently.  Similar to how OpenCV converts all images to a RGB format.  The referenced ffmpeg command does not need to do this pixel conversion because it is not doing the intermediate processing and just sending the packets from the decoder into the encoder.  My guess is that if `ffprobe` was executed against the out.h264 file created or the camera rtsp stream, it would report the different pixel format.

With respect to the overall objective of allowing for 6 cameras, the general method implemented within Motion is using dual streams with different resolutions.  This is accomplished via the `netcam_highres` with the `movie_passthrough` option.   These options bypass all the decode/encode processing for the high resolution stream and only perform them on the low resolution.

**Comment by rayzorben** [comment]
@Mr-DaveDev isn't this saying that it is indeed YUV420P ?
```
> ffprobe out.h264
Input #0, h264, from 'out.h264':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 2592x1520 [SAR 1:1 DAR 162:95], 99.40 fps, 100 tbr, 1200k tbn, 200 tbc
```

**Comment by Mr-DaveDev** [comment]
Yes it does.  If you want to just test whether the conversion is necessary, it is simple enough to do.

Just add a 
`return 0;`
[here](https://github.com/Motion-Project/motion/blob/d8ea81dc8c1fe4aa6907b3db0c576e2c6b956edf/src/netcam_rtsp.c#L39)

If it works, then you just need to get the ffmpeg pixel format that is being used and let us know it.  It can be added to the if condition.  (The "MY" variant in those names are simply for getting a consistent variable name across the different versions of ffmpeg )

**Comment by rayzorben** [comment]
Looks like the conversion may be necessary still? I added the `return 0` where recommended and i no longer get the conversion message, but the file it produces is just a thin green line. What is weird though is that I specified h264_cudiv and the output format seems to be x265?

```
x265 [info]: HEVC encoder version 3.2.1
x265 [info]: build info [Linux][GCC 9.2.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main profile, Level-5 (Main tier)
x265 [info]: Thread pool created using 8 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 1 / wpp(48 rows)
x265 [info]: Coding QT: max CU size, min CU size : 32 / 16
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : dia / 57 / 0 / 2
x265 [info]: Keyframe min / max / scenecut / bias: 15 / 250 / 0 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 0 / 0 / 0
x265 [info]: b-pyramid / weightp / weightb       : 0 / 0 / 0
x265 [info]: References / ref-limit  cu / depth  : 1 / off / off
x265 [info]: Rate Control / qCompress            : CRF-0.0 / 0.60
x265 [info]: tools: rd=2 psy-rd=2.00 early-skip rskip tmvp fast-intra
x265 [info]: tools: strong-intra-smoothing lslices=8 deblock
[1:ml1] [NTC] [EVT] event_newfile: File of type 8 saved to: /mnt/security/motion/20-front-porch/1-01-20191123123827.mp4
[1:ml1] [NTC] [ALL] motion_detected: Motion detected - starting event 1
x265 [info]: frame I:     26, Avg QP:0.00  kb/s: 379234.18
x265 [info]: frame P:    150, Avg QP:0.38  kb/s: 67380.55
x265 [info]: consecutive B-frames: 100.0% 

encoded 176 frames in 33.38s (5.27 fps), 113449.84 kb/s, Avg QP:0.32
[1:ml1] [NTC] [ALL] mlp_actions: End of event 1
```

**Comment by Mr-DaveDev** [comment]
Well, it was worth a try.  There does not seem that there is anything that can be done on this end to eliminate the requirement to change the pixel format.

**Comment by rayzorben** [comment]
Thanks, I have got CPU usage down when there is no motion to 80-90% (so a single core) with decoder h264_qsv.

Is there a way to specify the encoder as well, or is the same used for both?

**Comment by Mr-DaveDev** [comment]
I'd recommend checking the guide.

**Comment by rayzorben** [comment]
@Mr-DaveDev OK, so I guess I wasn't being diligent in checking my camera feed. When using `netcam_decoder h264_qsv` the image is just green. The following ffmpeg command works fine for me: `ffmpeg -rtsp_transport tcp -y -hwaccel qsv -c:v h264_qsv -i 'rtsp://user:pass@192.168.0.20/cam/realmonitor?channel=1&subtype=0' -vcodec h264_qsv ~/out.h264`

I see the following errors in the log
```
[2:nc2:Front Porch] [INF] [ENC] ffmpeg_avcodec_log: bad src image pointers
[1:ml1:Front Porch] [NTC] [ALL] Above message repeats 20 times
[1:ml1:Front Porch] [NTC] [ALL] image_ring_resize: Resizing pre_capture buffer to 50 items
[2:nc2:Front Porch] [INF] [ENC] ffmpeg_avcodec_log: bad src image pointers
^C[1:ml1:Front Porch] [NTC] [ALL] Above message repeats 305 times
[1:ml1:Front Porch] [NTC] [ALL] mlp_actions: End of event 1
[2:nc2:Front Porch] [INF] [ENC] ffmpeg_avcodec_log: bad src image pointers
```

**Comment by Mr-Dave** [comment]
This issue has been relabeled as an enhancement to implement a HW decoding using qsv since that codec requires its own unique processings.

**Comment by aartrost** [comment]
Hi Everybody!

Any updates on this? I would love to be able to offload the decoding of incoming RTSP streams to the my server's iGPU. Would also be great if this can be used to offload some of the load when using Live Streams watch the camera's through an interface like MotionEye.

**Comment by gusarg81** [comment]
Hi, I am asking the same since this will save more CPU usage by using Intel Quick Sync hardware acceleration (since specifying netcam_decoder h264_qsv does not work due its different pixel formatting, which requires to specified like these [examples](https://trac.ffmpeg.org/wiki/Hardware/QuickSync)).

Thanks.

**Comment by Mr-Dave** [comment]
It is important to note that there is a distinct difference between the encoding process and the decoding process.  

What is indicated by @gusarg81 is not precisely accurate.  The decoder of `h264_qsv` does not work because that particular decoder requires unique headers, functions and processes that are only associated with `h264_qsv`. As can be seen in the initial comment on this issue, Motion can handle different pixel formats being sent from the decoders with additional CPU usage.  The pixel format error issue is only for encoding movies.  

For this issue of using the 'h264_qsv', I will indicate it is highly doubtful that I would implement it for either a decoder or encoder.  Instead there is now VAAPI support that was recently added as an option for netcam_decoder and for encoding, this functionality has always been available using the `movie_extpipe` option.  

For those that would still want to use the `h264_qsv`, there is an option to use a v4l2 loopback device or consider revising their own version of the Motion code.
