### ISSUE TITLE
Move noise tune constant into a configurable config varibale

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#1130]
Reported on the mail list: https://sourceforge.net/p/motion/mailman/message/36949794/

https://github.com/Motion-Project/motion/blob/master/src/alg.c#L389
```
    /* 5: safe, 4: regular, 3: more sensitive */
    cnt->noise = 4 + (cnt->noise + sum) / 2;
```
Make this constant a config variable so it can be changed without recompiling

**Comment by flya320** [comment]
The Patch

[motion-4.3.1-use-noise_level-as-delta.txt](https://github.com/Motion-Project/motion/files/4807669/motion-4.3.1-use-noise_level-as-delta.txt)

changes the behavior of noise_level / noise_tune as follows:
If noise_tune is active, the value of noise_level is used as a delta added to the dynamically created noiselevel setting, instead of not using the noise_level value at all.

Examples:
noise_level 20
noise_tune off --> same behavior as before: fixed noise level at 20.

noise_level 0
noise_tune on --> same behavior as before: dynamically created noise level.

noise_level 10
noise_tune on --> dynamically created noise level with a delta 10 added.

regards,

thorsten
