### ISSUE TITLE
How to enable hardware acceleration?

### ISSUE THREAD

**Issue by vekexasia** [Motion-Project/motion#1137]
Hello, this is a question,

i've read some issues about cpu usage:
 - #976 
 - #560 
but none of them really tells me how to enable hardware acceleration.If any i didn't find the flag for the motion config file.

I'm testing motion (with motioneye) with 6 cameras streaming fullhd or 4k (asking motion to downscale to 720p). This eats all my i7 3770k cpu.

**Comment by tosiara** [comment]
It is better to ask questions on the mail list. There are more people to answer. Issues are only for technical bugs

**Comment by HJSK** [comment]
This maybe a solution for you? 
https://www.reddit.com/r/raspberry_pi/comments/5677qw/hardware_accelerated_x264_encoding_with_ffmpeg/

**Comment by usernamepi** [comment]
I wrote about hardware acceleration while I was still figuring out how to handle multiple high resolution cameras. Hardware accelartion turned out to be difficult.
I ditched it in favor of the solution to use two streams for each camera, which is supported by motion:
1. a low resolution stream (480p (480x640)) to be used for motion detection only.
2. a full resolution stream to be used for recording events. This stream is "passthrough", it will not be decoded or encoded.
Prerequisite: the cameras must support two streams (channels), most modern cameras do.
See the manual on how to accomplish this.
CPU usage will drop due to the low resolution processing for motion detection.
You will lose the motion overlay features in the highres recordings, since there is no decoding/encoding done.

**Comment by ministryofsillywalks** [comment]
> 
> 
> I wrote about hardware acceleration while I was still figuring out how to handle multiple high resolution cameras. Hardware accelartion turned out to be difficult.
> I ditched it in favor of the solution to use two streams for each camera, which is supported by motion:
> 
>     1. a low resolution stream (480p (480x640)) to be used for motion detection only.
> 
>     2. a full resolution stream to be used for recording events. This stream is "passthrough", it will not be decoded or encoded.
>        Prerequisite: the cameras must support two streams (channels), most modern cameras do.
>        See the manual on how to accomplish this.
>        CPU usage will drop due to the low resolution processing for motion detection.
>        You will lose the motion overlay features in the highres recordings, since there is no decoding/encoding done.

How exactly did you set it up?
Where can I tell Motioneye to use two different streams, one for detecting and one for recording?

**Comment by usernamepi** [comment]
Ai ... motioneye.
That is a different thing, different project.
I'm using "just" motion.
I checked the motioneye issues.
It seems to offer passthrough, see https://github.com/ccrisan/motioneye/pull/1533.
If you search the issues there is also some chatter about highres, so I suspect it is possible, but you may have to ask the motioneye community for support.

Motion on it's own supports it.
First of all you must configure the camera itself to produce a highres and lowres stream.
Next configure motion to use both streams. 
These are the relevant parameters in a motion configuration file:
# Low res  URL used for motion detection (your camera may offer a different url!)
netcam_url rtsp://xxx.xxx.xxx.xxx/Streaming/Channels/2

# High resolution URL used for recording (your camera may offer a different url!)
netcam_highres rtsp://xxx.xxx.xxx.xxx/Streaming/Channels/1

# Passthrough recording for high res URL
movie_passthrough on

# Image width (pixels), use lowres!
width 640
# Image height (pixels), use lowres!
height 480

# Passthrough image dimensions does not need to be configured (they are in the recording)
