### ISSUE TITLE
Saved video is frozen

### ISSUE THREAD

**Issue by jbnjohnathan** [Motion-Project/motion#1228]
0. Reviewed guide and contributing documents? (Yes):
1. version [4.3.1-1]: 
2. installed as a package or compiled from sources [deb,]: 
3. standalone or part of third party [motion]: 
4. video stream source [V4L (card or USB),]: 
5. hardware [ARM (rasberry Pi]: 
6. operating system [raspian 10]: 

I have the following config for video output

```
############################################################

# Use ffmpeg to encode videos of motion (default: off)
ffmpeg_output_movies on

# Use ffmpeg to make videos showing the moving pixels (ghost images) (default: off)
ffmpeg_output_debug_movies off

# Bitrate to be used by the ffmpeg encoder (default: 400000)
# This option is ignored if ffmpeg_variable_bitrate is not 0 (disabled)
ffmpeg_bps 1500000

# Enables and defines variable bitrate for the ffmpeg encoder.
# ffmpeg_bps is ignored if variable bitrate is enabled.
# Valid values: 0 (default) = fixed bitrate defined by ffmpeg_bps,
# or the range 1 - 100 where 1 means worst quality and 100 is best.
ffmpeg_variable_bitrate 0

# Container/Codec output videos
# Valid values: mpeg4, msmpeg4, swf,flv, ffv1, mov, mp4, mkv, hevc
ffmpeg_video_codec mkv

# When creating videos, should frames be duplicated in order
# to keep up with the requested frames per second
# (default: true)
ffmpeg_duplicate_frames true

# Interval in seconds between timelapse captures.  Default: 0 = off
timelapse_interval 0

# Timelapse file rollover mode. See motion_guide.html for options and uses.
timelapse_mode daily

# Frame rate for timelapse playback
timelapse_fps 30

# Container/Codec for timelapse video. Valid values: mpg or mpeg4
timelapse_codec mpeg4
```

The video files are created at the destination, and they are varying sizes, which is expected.
When I play them they are different lengths as well, as expected.
But only the first frame is shown, and that is the only frame frozen while the video plays.

I had an older version of motion before, so I upgraded to 4.3.1-1 to see if it was a bug in the older version but the problem remains.
It only seem to happen when I choose .mkv as format. I tried changing from `mpg` to `mpeg4` but no difference.
If I select `ffmpeg_video_codec mp4` instead the video quality is not very good, which is why I want to use mkv.
I had it working before, but not sure if something changed.

**Comment by jbnjohnathan** [comment]
I just thought of trying another video player. I had used VLC but now I tried Windows Media Player. And behold, the video plays as it should! Strange.
I was using VLC 3.0.4 on Windows 10.

**Comment by Mr-Dave** [comment]
Well, I do see this 

> ffmpeg_duplicate_frames true

Which is an option that should (in my opinion) be entirely eliminated.  Because when you duplicate frames to keep up with some frame rate, the result is that videos look frozen.  This is even indicated in the [documentation](https://motion-project.github.io/motion_config.html#movie_duplicate_frames).  

The probable reason for one player working vs another is due to the timings on the frozen section and how each player chooses to handle these duplicates.  Windows Media trusted the timings provided and played all the duplicate frames in an instant....VLC did not believe the timings on the frames and decided to show all of them and come up with its own timing.  

The future fate of this option will be "contemplated".
