### ISSUE TITLE
Shadows and clouds

### ISSUE THREAD

**Issue by dragonpiper** [Motion-Project/motion#1241]
Is there anyway to deal with these types of shadows. threshold doesn't work because shadows can create huge swings in changed pixels. https://i.imgur.com/tpxCuEp.jpg

**Comment by tuxthepenguin84** [comment]
A mask_file should work, "If you have one or more areas of the camera image in which you do NOT want motion detected (e.g. a tree that moves in the wind or a corner of the picture where you can see cars/pedestrians passing by) you need a mask file"
https://motion-project.github.io/motion_config.html#mask_file

**Comment by Mr-Dave** [comment]
Shadows are really hard to filter out.  Small little changes over large area could possibly be addressed by increasing the noise paramater.  You can also try the despeckle filter that makes sure that it is a big section that is trigger the motion rather than an accumulation of many scattered changes.  And of course the last option is to use the mask file as previously indicated.    

Ultimately, it is user specific tuning process.  I usually send a couple of movie files generated back through Motion and specify `stream_preview_method 3`  to fine tune the detection as much as possible.
