### ISSUE TITLE
Git Branching

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#128]
This is a continuation of the discussion on the mailing list.  The issue is moved to here so that regular motion users don't get spammed with the development talk.  I definitely want to have this discussion to make sure we establish things correctly from the start and don't have to change branching/tagging strategies later.  

As alluded to in the emails, the process that I had started in the repo was a unstable, master and release branch method.  The unstable is where I initially committed items to test whether they work, see what else needs to be added that wasn't included, etc.  The master branch is the "we think it is all good" branch and yet more testing.  This would be effectively the "stable" branch.  The last would be to create branches for a release which would have what we package and send to the deployment teams.  If security or packaging requirements arise, then they would be put onto the appropriate release branch and also put into unstable.  I now observe that this does seem to a unique structure and am open to discussing alternative strategies.  But want to understand how particular issues are addressed.

When I looked at the samples provided what I observed (correct me if I get this wrong), is basically a few strategies.  A single master which I presume to be the development branch and then various tags for releases.  We also have a master and branches for releases.  And finally, there is master and branches for feature changes or enhancements.  

The problems that I was trying to address were the following that I'd like to know how they'll be addressed with an alternative stragegy:

1.  I have experienced and also observed other users on some projects like ffmpeg, getting the repo, sticking on the master repo and only later observing that it is a development in progress.  This is an especially difficult problem for this project because many of the people getting the code don't have experience compiling code.  This "should" be significantly reduced once we have packages of the debs and RPMs and then in a few years have it automatically in distributions.  So the problem I'm looking to solve, is how to have area for stable code not yet in a release as well as an area that we can test changes, pull requests, etc for evaluation?

2.  For the various repos that use tags, what will be our strategy for getting things like security fixes, small packaging requests into them?  While I haven't seen any of these come through, I do want to plan so we know what is the strategy.  If the releases are designated as tags, I suppose it could be branched if a urgent need comes in to address it, but then we'd be left with a mess.  If we say that it will be in the next release, then it could be a significant amount of time until it gets resolved.  We'd need to finish whatever we were in the process of changing before it gets out.

For the branching for feature changes, what I'd worry about is the proliferation of branches and changing the repo from a tree into a bush.  As stated above, I'm open to alternative strategies but want to make sure that we have the issues addressed so please feel free to comment.
Dave

**Comment by jogu** [comment]
Absolutely recognise these problems, these are good things to be discussing!

> 1. ... how to have area for stable code not yet in a release as well as an area that we can test changes, pull requests, etc for evaluation

It's definitely a tricky area.

There are really two main approaches that can be taken:

a) all code that goes to master should be at the point where it is believed to be stable enough to go into a release.

or:

b) code only goes to master once it is fully tested and actually ready for release

(The difference between the two is pretty subtle!)

The potential issue I see with "b" is that it means it can take a long time for code to make it into a release or to master, and it results in (potentially error prone) merges right at release time - and there is a tendency for things to stall because it's hard to do sufficient testing.

Even with 'a)' it is expected that someone can checkout the code from master and it will work. If it is found not to work, fixing it is high priority. With a) you tend to have more people using the code before the release, so problems get found and hopefully fixed sooner. (With b) it tends to only be actual developers that are trying out the code for an upcoming release.)

> For the various repos that use tags, what will be our strategy for getting things like security fixes, small packaging requests into them?

I think release branches are perfect for that. I think any approach we take has a strong possibility we'll need to provide a security fix for an older release, release branches are really the only way to do it. (Some projects take the "tag the release, and if we find we need to fix it, go back and create a branch" approach. Either way works.)

> For the branching for feature changes, what I'd worry about is the proliferation of branches and changing the repo from a tree into a bush.

Definitely a worry. The only reason to do a feature branch in the **project** repository were if multiple people were working collaboratively on a large feature, or there was a desire to publish it to try and encourage more people test it prior to a merge. The branches should be as short-lived as possible, merged back to master (if possible as a fast-forward merge so if you look at the history on master it's not actually visible that the work was done on a branch) and in many cases people advocate deleting the branch to keep things clean.

Random article that describes topic branches (and a similar branch workflow to the one I favour) a bit:

https://blog.mozilla.org/webdev/2011/11/21/git-using-topic-branches-and-interactive-rebasing-effectively/
(I tend to prefer to only work on one thing at once, so only create a topic branch in my personal repo if I need to create a pull request for a sub-set of my master or need to temporarily pause some work.)

**Comment by joerg-w** [comment]
Let me explain how things have been handled, when SVN was our workflow tool:

'Trunk' was the development branch, where stable patches have been commited. Users were recommended to use 'trunk', if they were looking for the latest stable code. I would compare 'trunk' to Dave's 'master' branch.

There was nothing like an 'unstable' branch though. Patches were developped offline and after some (private) testing, they were posted on the Wiki. After some more testing, such patches were committed to 'trunk'.

Releases were built from 'trunk', making sure that the current 'trunk' was stable enough for a formal release.

This was not very much different from the unstable, master, release approach. But it was much less transparent and multi user (developer) friendly. I believe that Dave's approach is much more feasible and it supports the limited size of the project well enough. On the other hand I have to admit, that I have very little Git experience, so that I'm not in a good position to suggest any alternative.

**Comment by Mr-Dave** [comment]
Ok, so are we in agreement on branches for releases?  Still need to discuss naming scheme for them.  Although I created the one for 3.4, I didn't think my repo would ever be upstream so I wouldn't want to perpetuate that naming.  

For the master, I think that we're also agreeing that it needs to be a ready to go and not be a work in progress area.  

Which I think leaves just the where to put work in progress.  If I understand the article correct and your comments, the WIP would be in our personal repos.  And then within there, would be pretty much the choice of whether you're doing a feature branch or just doing it on a different branch.  I think I may be able to get on board with this.  I did observe that this is how the linuxtv part of the kernel is managed.  Lots of developer repos listed under the main repo...But more questions.  I'm guessing I'm going to need to get a new GIT id.  I can't have a Motion repo under my existing ID because the internet has linked to Mr-Dave/motion.  That now redirects to here.  Any slick solution that you know?  Next question is how we'll handle pull requests from others.  Many are not going to be in a release status.  I "think" we can grab those pull requests into our own repos, work them, then push them back to the project master when done from our personal repos as a pull request.  But does that keep the attribution?  We'd have to ultimately kill / cancel their original pull requests wouldn't we?  Then that cancel would send notifications that it was rejected even if it wasn't?  

Did I summarize and interpret this correctly?

**Comment by jogu** [comment]
Your summary and interpretation sound spot on.

> Ok, so are we in agreement on branches for releases? Still need to discuss naming scheme for them. Although I created the one for 3.4, I didn't think my repo would ever be upstream so I wouldn't want to perpetuate that naming.

Yep. I don't mind on naming, though obviously consistency is good. 3.4, motion-3.4 or release-3.4 would seem to be good options, any work for me. I don't think any body has branched off the existing branches, so we could rename all the existing branches to match any new scheme.

> For the master, I think that we're also agreeing that it needs to be a ready to go and not be a work in progress area.

Agreed.

> I can't have a Motion repo under my existing ID because the internet has linked to Mr-Dave/motion

D'oh. That's one thing I hadn't thought of! I'm not sure. You could have a motion under Mr-Dave but with a different repo name (Mr-Dave/motion-project or something), the github staff might have to help setting up that one so that it's part of the "network" (I think the "fork" button is hard wired to always use the same repo name).

Alternatively, I don't imagine anyone would object if you used some feature branches etc in the main project for your own work in progress. :)

> Next question is how we'll handle pull requests from others. 

There's a few ways I've seen it done.

One is to review and cajole contributors into fixing things so they're ready.

If you pull them into your own repo, that will preserve the original commit author by default. (and you'd then close the pull request manually with a comment sayings "Thanks, I've pushed this to the repo now, with a couple of extra fixes I spotted" etc.)

**Comment by Mr-Dave** [comment]
I'll see what I can do on the ID.  If needed, I will take one for the team and find a new one.  I don't want to "pollute" the project repo.  Lets go with having the release branches as release-version number (prefix with release-) .  

Lets also make sure to monitor that the attribution on the pulls stays correct when pulled.  Even if the cajoling doesn't work and we have to change a lot, I want make sure the attributions are correct.  

I think that this closes out the issue/ branch plan.  I'd like to leave the issue open for a bit however for others to comment if they think differently.

**Comment by jogu** [comment]
Sounds good to me! It might be worth asking the github staff if they have any suggestions that avoid the need for a new id - they're very good and quick to respond - https://github.com/contact

**Comment by jogu** [comment]
> I'll see what I can do on the ID. If needed, I will take one for the team and find a new one. I don't want to "pollute" the project repo

I figured this out. I believe you should just be able to fork the project motion repo like usual; github should spot that "motion" is already in use in your repo and create the new fork as motion-1 instead, and then you can rename it to whatever you want (apart from "motion" of course!). [Certainly this is how it works if I try to fork someone else's motion repo having already forked your repo.]

**Comment by tosiara** [comment]
I like the current Mr-Dave's workflow "unstable-master-release" where:
unstable contains all current patches and fixes that still require testing
master gets merged with unstable as soon as fixes are well tested - stable trunk
release is freezed snapshot of master with version tag

Would be great to set `unstable` as default branch for pull requests. So we don't waste time asking users to re-implement the patch on unstable

**Comment by Mr-Dave** [comment]
Lets see how the workflow of the project maintainers using their own repos as the "unstable" branch.  This is how the other projects work.  It also helps us keep the project repo "clean".  If needed, we can review others work, clean up stuff, squash commits together, snip our own branches, etc.

**Comment by tosiara** [comment]
Sorry, I didn't get. In short: do we accept new patches directly into `master` or into `unstable` first?

**Comment by jogu** [comment]
My understanding (and I'm happy to be corrected):

If patches are good enough they go straight to master. Example: https://github.com/Motion-Project/motion/pull/129

If they need changes by one of the core team, that's done in their own repo. https://github.com/Motion-Project/motion/pull/138 is probably a decent example. MrDave needed to make fixes to what I'd originally submitted in a different pull request, so created a branch in his repo to do so.

"unstable" branch is not used. If an "unstable" branch is needed (eg. several project members working on a big new feature and want to break things temporarily) we create a topic branch in the main repo.

**Comment by tosiara** [comment]
So if I now submit experimental patch into unstable we may get merge conflict because master is already ahead. This makes no sense to me

**Comment by jogu** [comment]
"So if I now submit experimental patch into unstable <...>".

The unstable branch is not used.

**Comment by tosiara** [comment]
Can we drop it so it does not mislead others?

**Comment by Mr-DaveDev** [comment]
Yes, I have to now use a different ID, email and development computer.  It is the only way in which git allows for the automatic redirection to the project.  (User group mailing list archive, AskUbuntu, PI forums, etc, etc).  This also maintains the links where in comments in other user repos, it said things like...go see the Mr-Dave issue #26. 

Regarding the unstable, snipping branches makes me **extremely** nervous.   We need to be positive that we are not going to lose something and I'd prefer to let it sit there unused until it is obsolete.  

For the process, this is just going to be similar to how you worked with my repo in the past.  You did your work on your fork and as you created code there and tested it, you put a pull request to the Mr-Dave repo.  The difference is that now the pull request goes to the project.  

One revision to the workflow however is that I'd like to try to implement a process by which you don't implement your own pull into the project.  If you created the pull, the other maintainers should be reviewing it before it goes to master.  Trivial change log sort of stuff may be an exception but for most of the items if we have multiple  people on the maintainer list, then we should be reviewing each others work.

**Comment by Mr-Dave** [comment]
@tosiara I am going to close this.  Let me know if it is still unclear

**Comment by tosiara** [comment]
Well, instead of having two branches (unstable and master) at one repo we now have distributed different commits across different branches in different (personal) repos. I'm really confused which tree should I now use if I have an idea for some patch. 
But anyway, this is my personal view. I will stay will majority choice, not a big deal really

**Comment by jogu** [comment]
The idea is that in general anything worthwhile will very quickly make it to master on the project repo, so always develop ideas against that. If there's something worthwhile and not making it to master quickly because it's a large development, you should hear about it via one of the mailing lists etc :)

ie. other than anything that is still a work in progress, everything will be on master.

**Comment by jogu** [comment]
Not sure if this is the best place to discuss it, but not sure if there's any better place either:

I noticed from https://github.com/Motion-Project/motion/wiki/News that MrDave will soon run out of time. I just wondered what is planned to happen in the Nov 2016 -> Aug 2017 period - I think MrDave has basically been the only one reviewing my pull requests.

I guess it's perhaps unlikely we'll put out any new releases over that period (certainly I don't currently have enough different versions of ubuntu/debian available to build the release .deb packages - though I guess we could use a service like https://en.wikipedia.org/wiki/Open_Build_Service which appears to support at least most of the platforms we current build debs for).

It'd be nice if development didn't grind to a complete halt over this period though.

**Comment by joerg-w** [comment]
Joseph,

maybe you can collect all the stuff in your repository during this period. Dave can then pull it into his repo when he returns. Users who are looking for the latest code can download your repo at any time if they don't want to wait for a formal release. Just like they did with the SVN trunk before.

**Comment by tosiara** [comment]
Guys, why can't we get back branching and keep everything in a single repo? This is really confusing people - where is the latest version? which is stable and which is experimental? Which repo to use: MrDave? MrDaveDev? jogu? any other personal repo?

Can we have all the branches in one project with names that meets users expectations, like "unstable", experimental", "release-xx", "mmal-beta", "cmake-wip" etc. It is common practice in other projects so would be nice if we also follow easy standards

**Comment by slokhorst** [comment]
@tosiara Everyone should use the [Motion-Project/motion](https://github.com/Motion-Project/motion) repository. The *master* branch for the actively developed, possibly untested, latest version, or the *4.0* (or something like that) for one of the stable branches.

There should be no need to use another repository, such as that of @jogu or me. Except when you want to test a feature they are developing. Until they are merged into **this** (Motion-Project/motion) repository, you should consider them unofficial, unstable, and not to be used by the public.

**Comment by jogu** [comment]
Hi Joerg,

> maybe you can collect all the stuff in your repository during this period. Dave can then pull it into his repo when he returns. Users who are looking for the latest code can download your repo at any time if they don't want to wait for a formal release. Just like they did with the SVN trunk before.

It's an option, but not one of my favourites. It basically means if users find problems in the main repo code, I (personally) won't be able to fix them - I have the necessary access to actually do so, but our current policy (as per https://github.com/Motion-Project/motion/issues/128#issuecomment-241024043 ) is that another project member should review the changes before they go into the main repo. If I was to be able to merge my own changes into the main repo we either need to relax that policy or get more project members reviewing changes - to date as far as I know only myself and MrDave have reviewed any changes.

**Comment by Mr-Dave** [comment]
1.  I think we'll need to relax the policy.  I'll still be able to read the email notifications but probably won't be able to provide testing/thoughtful reviews. 
2.  I'm unclear on why there is still confusion on the branches.  This is just like it was when we were under Sack except we can merge in the pull requests versus just having them sit there.  Everyone develops on their own fork and submits pull requests.  
3.  I would agree that the unstable can be snipped.  
4.  Generally, I wasn't thinking that there would be a release during this time.  If it was just the debs, then that isn't much effort anymore since we have the auto build script.

**Comment by jogu** [comment]
Thanks MrDave. That seems like the best approach in the circumstances.

I'd not realised the unstable branch still existed. That was merged back into master back in 2015 as far as I can see - I've deleted the unstable branch from the main repo now, hopefully that will remove any remaining confusion. (Note, it'll show up in your local copies till you do `git fetch --prune`)
