### ISSUE TITLE
Follow movement PTZ

### ISSUE THREAD

**Issue by fjramirez1987** [Motion-Project/motion#1316]
Is it possible to obtain a value (x, y) of the area where motion is detected? I wanted to use that value to move my PTZ camera to the area where motion is detected.

**Comment by genius3000** [comment]
For future reference this is a question that should have been asked on the mailing list rather than the development issues.

You can use [on_motion_detected](https://motion-project.github.io/motion_config.html#on_motion_detected) with [conversion specifiers](https://motion-project.github.io/motion_config.html#conversion_specifiers) to accomplish this. It's all documented in the guide.
