### ISSUE TITLE
netcam_url does not work because image size is not modulo 8

### ISSUE THREAD

**Issue by int2018** [Motion-Project/motion#1322]
0. Reviewed guide and contributing documents? (Yes/No): No
1. version [x.y.z, hash, other]: 4.0.1 (on Raspberry Pi Model B Plus)
2. installed as a package or compiled from sources [deb, rpm, git, other]: standard deb
3. standalone or part of third party [motion, MotionEyeOS, other]: no
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: mjpeg 
5. hardware [x86, ARM, other]:  Linux raspberrypi armv6l GNU/Linux (Raspberry Pi Model B Plus)
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Linux raspberrypi 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 

Hi all,
before I start updating the "old" Jessie towards something newer, I like to know if the issue can be solved on Jessie?
(and maybe updating the os is not the solution)

The issue is this:
I use an old mobile phone as a webcam and the it delivers 1278 x 718 pixels.
When I use netcam_url with the rtsp stream it works and the next best size is chosen which is 1280x720 pixels.
But the rtsp stream makes too much load on the  old raspberry.

But when I use netcam_url with a mjpeg or plain jpg single picture stream I get the error that the image size is invalid because it is not modulo 8.
This is strange because I seems to ignore my height and width settings and keeps "detecting" the image size and then it doesn't like it.

I am trying to run this on an "old" Raspberry Pi Model B Plus
I am not sure, but I thought I did not have this issue on a Raspberry Pi 3 Model B Rev 1.2 (arm71)

So which option do I have?
- Maybe it is a configuration issue. Is there some kind of setting which forces to use height and width setting?
- Currently I am runnnig 4.01, is the issues solved with a newer version of motion ?
- Do I have to update to Butster or Stretch and then update to a newer version of motion ?
- Or is it an "old hardware" issue and cannot be fixed?

Thanks for a hint

**Comment by int2018** [comment]
hm... issue is simply "closed" without any further information?
Is there a change in the "politeness policy" which I didn't get ?

SOME words would be nice, e.g. "correct, your hardware us too old" or "issue is solved, check  #1234" or "version 4.01. is not supported in the issue section, try updating" or "we don't support raspberry anymore" or even "you did not mention xxx and thus we cannot help you"

Come on, "Mr-Dave" , take 10-20 seconds and just write a tiny explanation before you just close an issue!!

Thanks in advance!

**Comment by Mr-Dave** [comment]
> Is there a change in the "politeness policy" which I didn't get ?

Actually, it isn't a change but I will try to answer this one for your benefit.  

Generally, posting to an issue log you should check the rules/guidelines associated with it.  Indicating that you haven't expended the effort to read what was written in guides or instructions can be viewed as quite rude to the developers because you are indicating that your time is more valuable than theirs.  This is even more so the case when one of the documents is a single page and the questions posed seem to imply that little to no effort has been expended to answer the questions independently.

**Comment by int2018** [comment]
On the contrary!
With my initial post and the question what would be the next step in this issue, I tried to save MY AND YOUR time.
Your indication is wrong that I didn't make an effort to solve the problem. As you could see by reading my issue description I was quite "deep" in the research which brought me to the height/width/modulo question.
I was posting this issue here because after all I could not solve the problem myself. And before investing more time I just wanted to ask if it is worth it or if the effort is pointless.

So, a simple answer "old hardware, forget it" would save MY time trying to digging further into the problem. (get log files etc.) and YOUR time.
And a "quick" answer could point into the right direction, e.g. "please read post #1234" or "in order to go further please check if you have lib xy installed" or whatever.

...and writing an explanation why you closed the issue without a comment took more time than solving it.
Maybe "the rules" should be extended that it is not allowed to close a request without leaving a decent comment. 
Because such behavior could be (mis)interpreted as arrogant.

Best regards and stay healthy

**Comment by int2018** [comment]
Pardon??? "unwanted" comments are simply marked as "off-topic"??
And again without ANY comment about the content??
In my reply I tried AGAIN to point out the initial TECHNICAL issue and you just declare it as off-topic?
WHO defines what is "off-topic"?
Such behavior confirms all the prejudices about administrators misusing their role and power... 

Maybe you should apply for a job in some regime which just muzzles people who don't agree?

AGAIN: my initial post and also my try to focus on the TECHNICAL aspects gives NO REASONs for such actions!

Please return to yourself and focus on the problem!

Best regards

**Comment by Mr-Dave** [comment]
Since you did not read the instructions or contributing document for opening an issue on this site, the questions and complaints are not appropriate and off topic.  "On Topic" for this issues log on github are code issues, crashes and enhancements.  It is positively not a "So which option do I have", or "Do I have to..." forum or place for complaints about this issue log not being what you would like it to be.  

This point of it being a code issue log and not a user forum is clearly listed in the first paragraph of the one page contributing document.  As previously indicated, please read the manual and contributing documents.  Other users can be consulted via the contact methods indicated in the contributing document who could likely readily answer the questions you posted here.
