### ISSUE TITLE
Audio recording

### ISSUE THREAD

**Issue by lolouk44** [Motion-Project/motion#146]
Hi,

I was just wondering whether there were any plans to include the audio to the recorded stream when available?

My camera has a built-in microphone and when using H264 / RTSP the audio is contained in the video, it would be nice to have the audio present in the recorded files.

Thanks
Laurent

**Comment by Mr-Dave** [comment]
No there is not.  The core functionality of the application is strictly video.

**Comment by lolouk44** [comment]
Too bad. Thanks for replying anyway.

**Comment by ZdenekM** [comment]
I understand, but when the cam is used for security purposes, it would make big sense to store also audio...

**Comment by Mr-Dave** [comment]
That would be illegal in many countries.

**Comment by starsprung** [comment]
It's worth noting both Nest (Google) and Ring (Amazon) cameras – two of the biggest players in home surveillance – both record audio. In some circumstances it might be illegal to record conversations without consent, but literally any audio recording device could be used for such a purpose and audio recorders are not illegal simply because they _may_ be used illegally.
