### ISSUE TITLE
Onvif cams not working after update moition to 4.5.1

### ISSUE THREAD

**Issue by zajaaczki** [Motion-Project/motion#1665]
### Did you read the guide?

Yes

### What is the base version number of Motion being used?

4.5.x

### What was the install method?

Built from source code

### What is base architecture?

ARM-64bit

### What is the distro being used?

Debian

### Disto version number

bullseye

### Camera type(s) being used?

Network camera with RTSP, Other

### Describe the issue/problem and steps to reproduce

I have several imou cams with onvif all work ok with motion 4.3.2 but after update to 4.5.1 all dead. Still works good with vlc, different rtsp cams work fine with motion. 
RTSP stream:
rtsp://192.168.55.1:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif

### Motion log output at log_level 8

```shell
[1:ml1:Camera1] [ERR] [NET] netcam_rtsp_open_context: norm: Unable to open camera(Camera1): Invalid data found when processing input
[1:ml1:Camera1] [ERR] [VID] vid_start: Netcam RTSP failed to open
```

**Comment by RegProctor** [comment]
Same here. The only thing I noticed that might be a clue as to why is that my two newer cameras were fine but two out of three of my older cameras have failed with the same `RTSP failed to open` message as above.

**Comment by Mr-Dave** [comment]
No full log was posted as requested in the template so we can not determine much...did you try using the `netcam_params`? e.g. `netcam_params allowed_media_types="data;video" `

**Comment by RegProctor** [comment]
> No full log was posted as requested

Where is this log generated you want? Tell me how to collect it and I will get it to you.

**Comment by Mr-Dave** [comment]
What was posted was a one line snippet from the log.  If you specify in the configuration a `log_level 8` and then specify a log file (or just to console and copy/paste from there) it shows much of the information we'd need.  It shows the user parameters as well as many messages.  See the other issue reported for [v4l2_cleanup](https://github.com/Motion-Project/motion/issues/1662) and what that user provided as the output at log_level 8.  (I would prefer English however :) ) 

I'd say that I'd really suggest trying the option `netcam_params allowed_media_types="data;video"`  I think that may do it..but don't know if that was already specified or whether the log will report some other error when that is used.

**Comment by RegProctor** [comment]
[motion.stdout.txt.gz](https://github.com/Motion-Project/motion/files/11269189/motion.stdout.txt.gz)

I:

- Tried adding the line `netcam_params allowed_media_types="data;video"` to the two that didn't work, no difference.
- Elevated the log_level to 8 on the two that don't work.
- Created the attached with the following commands

```
motion start 2> motion.stderr.txt &> motion.stdout.txt
gzip motion.stdout.txt
```

**Comment by RegProctor** [comment]
[motion.tar.gz](https://github.com/Motion-Project/motion/files/11277832/motion.tar.gz)

**Comment by Mr-Dave** [comment]
Thanks.  The log shows that the 
`netcam_params allowed_media_types="data;video"`
was not specified in the default motion.conf file 

```[0:motion] [INF] [ALL] netcam_url                
[0:motion] [INF] [ALL] netcam_params             
[0:motion] [INF] [ALL] netcam_high_url           
[0:motion] [INF] [ALL] netcam_high_params        
[0:motion] [INF] [ALL] netcam_userpass           
```
nor in either of the camera files
```
[0:motion] [INF] [ALL] camera_dir                /etc/motion/conf.d
[0:motion] [INF] [ALL] Thread 1 - Config file: /etc/motion/conf.d/8086-IP-_61-Front-Left.conf
[0:motion] [INF] [ALL] target_dir                /srv/cctv/front-left
[0:motion] [INF] [ALL] netcam_url                <redacted>
[0:motion] [INF] [ALL] netcam_userpass           <redacted>
[0:motion] [INF] [ALL] width                     2304
[0:motion] [INF] [ALL] height                    1296
[0:motion] [INF] [ALL] text_left                 Front Left
[0:motion] [INF] [ALL] movie_filename            Front-Left_%Y-%m-%d_%H:%M:%S
[0:motion] [INF] [ALL] stream_port               8086
[0:motion] [INF] [ALL] Thread 2 - Config file: /etc/motion/conf.d/8087-IP-_50-Front-Right.conf
[0:motion] [INF] [ALL] target_dir                /srv/cctv/front-right
[0:motion] [INF] [ALL] netcam_url                <redacted>
[0:motion] [INF] [ALL] netcam_userpass           <redacted>
[0:motion] [INF] [ALL] width                     2304
[0:motion] [INF] [ALL] height                    1296
[0:motion] [INF] [ALL] text_left                 Front right
[0:motion] [INF] [ALL] movie_filename            Front-Right_%Y-%m-%d_%H:%M:%S
[0:motion] [INF] [ALL] stream_port               8087
```

Can you add the parameter?

**Comment by RegProctor** [comment]
No it was specified in the conf for the cameras that don't work. Why does it have to be in the main conf file?

**Comment by Mr-Dave** [comment]
Per the log file posted, it was **not** put into the camera configuration file.  It must be specified either as the default (in the motion.conf file) or within the specific camera configuration file.

**Comment by RegProctor** [comment]
[motion.zip](https://github.com/Motion-Project/motion/files/11291558/motion.zip)

Then there is something that needs to be reconciled in the setup because here is my exact conf file setup except for the passwords being X'ed. 

The two cameras that no longer work are in the conf files with the word "Garage" in their names. I think you will find that the line is in those two files. Further log level 8 was specified in those two files as well so I'm now questioning whether changing the default file to log level 8 had any real benefit since the logs seems to be indicating to you that which was done in the individual camera files was not done.

**Comment by RegProctor** [comment]
On a side note, is there a way on the main screen that shows all the cameras at once to specify the order that the cameras appear? I didn't find that bit of information anywhere I looked in the documentation.

**Comment by RegProctor** [comment]
[motion.stdout.txt.gz](https://github.com/Motion-Project/motion/files/11291694/motion.stdout.txt.gz)

Also, here is the log with that line, **_additionally_** to being added to the two failing cameras conf, in the default conf file.

**Comment by Mr-Dave** [comment]
@zajaaczki Since you opened the issue, can you also confirm that the additional parameter did not resolve the issue? 

Also, since you indicated that you built from source, can you rebuild with [this](https://github.com/Motion-Project/motion/blob/c28d41b2f7ee3a20dd65c5e158e126991de898c7/src/netcam_rtsp.c#L1348) line commented out to see if it resolves this issue.

**Comment by RegProctor** [comment]
@Mr-Dave I give you all of my setup and logs, I thought that would give you something to dig into and come back with.

**Comment by Mr-Dave** [comment]
@RegProctor Did you try to rebuild with the indicated change above?  Also, could you confirm that the url specified works with ffmpeg, ffplay and show the output using ffprobe?

**Comment by RegProctor** [comment]
> Did you try to rebuild with the indicated change above? 

Motion comes with my OpenSUSE distro. so I have never built it yet alone rebuilt it and I'm not a C programmer. I can certainly clone the repo but I'm going to need you to give me some steps to build it. If you do, I'm happy to try that. 

That said, Tumbleweed is a rolling distro. and therefore is about as up to date as you can get so if that change has made it to the distros. then it will almost certainly be in Tumbleweed by now.  Is there a way I can check that, like it's part of a particular version #?  

I haven't tried those cameras since my last post here so just in case that's a new addition that's only recently made it through, I'll try them again tonight. If it works I'll let you know straight away.

> Also, could you confirm that the url specified works with ffmpeg, ffplay and show the output using ffprobe?

I know the URL works through VLC, through the current ffmpeg, I can't say. I can only say that it used to, so sure, maybe something broke in it in recent times.

While I have used ffmpeg to convert files on disk I have no idea how to use it test a URL so a sample line would be appreciated. I didn't even know of the existence of ffplay & ffprobe. Also, I assume by URL you mean the URL's to the cameras that don't work? If you mean some other URL, please let me know what that might be.

**Comment by Mr-Dave** [comment]
On a command prompt, type
```
ffplay yoururlstring
```
and see if it opens a window and plays.  For ffprobe, it is same format, just that it print out information regarding what it sees at the url provided. For example, this is the output from one of my cameras that supports ONVIF
```
  Metadata:
    title           : 10
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2560x1920, 15 tbr, 90k tbn, 180k tbc
  Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s
```
 

Probably want to start with the above first.  

If you want to see the instructions for building, they are documented [here](https://motion-project.github.io/motion_build.html#BUILD_OPENSUSE).  You'd install the required packages, then clone the repo, make the revision to the one line [here](https://github.com/Motion-Project/motion/blob/c28d41b2f7ee3a20dd65c5e158e126991de898c7/src/netcam_rtsp.c#L1348) in the source file by just putting a ```//``` in front of the line then saving it.  Then run the other steps in the building instructions of 
```
cd motion
autoreconf -fiv
./configure
make
```
at the command prompt and finally start the compiled version by specifying 
```./src/motion -c /path/to/motion.conf ```

Note that if you a different instance of Motion running on the same computer, things may conflict so you may want to close the other instance or revise the configuration for the test to only point to the one camera and use different ports for the webcontrol and stream.  If it is running the new version, you will see that the version number will be different.
