### ISSUE TITLE
Move to a conf.d style directory structure

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motion#178]
This is a continuation of the discussion in pull request #154 The issue is whether the configuration files should be stored within a conf.d subdirectory structure such as what is being implemented in other applications.  

e.g.  Instead of just having /etc/motion/motion.conf and all the camera.conf files (formerly thread.conf) in that same directory, there would be a subdirectory such as /etc/motion/conf.d/camera.conf.

Pros:
1.  This seems to be the direction that other applications are taking.  (Lightdm changed to this between Debian8 and Ubuntu 16.04.) 
2.  If this is ultimately going to be implemented, the time to do this is now.  It would seem to be significant enough to need a major version change and the next version will be going from 3x up to 4.0.
3.  In the long term, this will make the motion configuration files consistent with how newer applications are handling configuration files.

Cons:
1.  There will be user confusion regarding where to make the changes.
2.  Users will need to manually adjust the configuration files from previous releases.
3.  Applications which use motion as the backend will be impacted and require revisions.  
4.  The pull request included code changes.  Need additional review for documentation and impacts to Makefile, debian packager rules/config, 

Unknown:  (could be a pro or con)
a.  Unsure about the impact on the web interface.  It is currently believed that if users request to add/remove a thread after motion has started, motion will crash.

Please add other pros and cons for discussion.  

Copying this issue to others that may have a interest in this issue:
@ccrisan 
@mterzo

**Comment by jogu** [comment]
con 1, 2 & 3: The change is backward compatible; if you don't specify a directory with the new config statement, you can continue to use the existing structure. ie. I build that patch and ran it with my existing config files without changing them and everything worked fine.

con 3: Are there many of these? MotionEye creates it's own config files and manages it's own instance of motion, so it's not affected by how the config files provided in the package are structured - it would 'just work' due to the backwards compatibility.

unknown a: I didn't know this was possible. How do you do that? I can only find quit / restart options at least when using a browser, nothing to add/remove.

**Comment by mterzo** [comment]
Con 4: It's in addition to. So still backwards compatible.

Con 3: motion eye could still do what it does today and later adopt the new directory. 

Unknown: I haven't seen this work. Do these features still work?

**Comment by Mr-Dave** [comment]
Part of my question was whether to just make the move completely to use the new configuration directory structure rather than just as an addition.  If we have it only as an addition, do we lose the "pros"?  Are there other pros to add?  Are the thoughts that this is a interim step and by version 5(?) we'd move completely to a new directory structure?  

I'll note that I actually like the option but want to make sure that we document and discuss new options since there are so many already.  I also need to understand what we'll need to put in the motion guide explaining the what/why/when for how long, etc.

**Comment by mterzo** [comment]
I don't see a problem with keeping both conf.d and include style config. I do think it should be camera instead of thread. At some point using thread to define an include should fail. 

As far as how long is all in what ever you feel the roadmap should be.  You could keep it indefinitely if you like.

**Comment by jogu** [comment]
I don't see a problem with having both. eg. I believe apache supports both styles and has for 10+ years.

**Comment by Mr-Dave** [comment]
closed via #189
