### ISSUE TITLE
CMake build system

### ISSUE THREAD

**Issue by slokhorst** [Motion-Project/motion#229]
I think we all agree that the current build system with `configure.ac` and `Makefile.in` is quite a mess. Personally, I use CMake for most projects since I find it much easier to use and more readable.

If we are open to switching to CMake, I would like to try to convert our current system. We could also keep both (temporarily?), if there are some arguments for keeping the autotools system.

Please let me know if this would be a wanted addition or if I shouldn't bother wasting time.

**Comment by jogu** [comment]
I think I'd say I'd cautiously optimistic about cmake, and I certainly don't actively like autoconf. I think I know the answer to these questions, I don't recall any project I've worked on that has used cmake, so to make sure:

Can it essentially be made to do all the things our current configure script does? eg. command line flags to enable/disable things / override paths.

Are debian etc are quite happy packaging things that use cmake?

Probably should also wait for MrDave to weigh in before investing too much effort.

**Comment by Mr-Dave** [comment]
I would agree with Joseph's concerns.  I think that we have too much on our plates already with the issues without taking this on.  Looking just at the issues on the project right now, we have some pretty big issues with the threading mess, ffmpeg 3.1, authentication, MacOSX, masked recording, etc.  Although the configure.ac is a mess, it does have the benefit that at least "so far" it isn't crashing the app, losing functionality, preventing legal uses, etc.

**Comment by slokhorst** [comment]
Ok, completely understandable. Let's revisit this somewhere after the next release.

**Comment by jogu** [comment]
I have to say, having discovered https://github.com/Motion-Project/motion/issues/234 I'm getting much keener on seeing the back of configure.ac :) Now that the branch for the 4.0 release has been taken I presume we'd be happy to try something like this.

I think my two questions got lost in amongst the previous discussion; I expect the answers are fine but wanted to double check with @slokhorst as he seems to know cmake a lot better than I do:

Can it essentially be made to do all the things our current configure script does? eg. command line flags to enable/disable things / override paths.

Are debian etc are quite happy packaging things that use cmake?

**Comment by slokhorst** [comment]
@jogu yes, that's all perfectly possible. I am not sure about the stance of Debian, but I'm quite sure they package some of the projects from [this list](https://en.wikipedia.org/wiki/CMake#Applications_that_use_CMake).

I am working on a pull request to show a proof of concept, so you can see what would change. I hope to have it ready soon.

**Comment by jogu** [comment]
> I am not sure about the stance of Debian, but I'm quite sure they package some of the projects from [this list](https://en.wikipedia.org/wiki/CMake#Applications_that_use_CMake).

Yep, that is an impressive link, thanks - some very major projects on that list! I think that completely dispels my worries.

**Comment by Mr-Dave** [comment]
So, it appears we have a slight difference of opinion on this issue or at least on the timing/implementation.  

I am very concerned about completely eliminating the autotools and do not want it eliminated as part of this cmake change.  While there is that list of projects packaged using cmake, it is important that the packager who works the debian changes uses cmake.  @infinity0 can you please comment. 

I also anticipate that there is also a significant number of unintended consequences to the users that we are not even aware of yet.  As I indicated in the previous response, there are some pretty big issues and problems with the code base as is

**Comment by jogu** [comment]
@Mr-Dave Would you be okay with running both systems in parallel for a while? Maybe plan to remove autoconf after 4.1 or after bedding cmake down for 6 months or something? (Assuming a positive reply from the debian maintainer).

I don't think we can tackle some of the other issues without tackling this; I gave up on trying to tackle MacOS as it takes me about 20 times as long as it should to get a change to configure.ac working everywhere - partly that's because I'm not great with autoconf, but I'm fairly certain it's also partly because the current configure.ac has evolved into something that's (in my opinion) fairly inconsistent, poorly commented and buggy. :(

**Comment by slokhorst** [comment]
Just to clarify: I think we also should keep both systems, at least for the foreseeable future. I removed the autotools stuff in my pull request to make clear what CMake needs. The pull request is just to show you guys what the CMake system would look like.

Besides that, please don't spend to much time on this right now if there are more important things to do. It is fine with me to revisit this in a few weeks or months, when everything else has settled down. The PR was just intended to get some early feedback, to know if this is something we *might* want in the future at all.

**Comment by Mr-Dave** [comment]
I am good with having both.  I just want to make sure we don't jump over to this without a lot of testing and completely working though all of the issues and scenarios.

**Comment by infinity0** [comment]
Debian has good support for CMake. However I personally don't know it very well, so please document how to enable/disable features somewhere. For example all I have to do [currently](https://sources.debian.net/src/motion/3.4.1-1/debian/rules/#L12) is pass some `--with-xxx` flags, with CMake it would be something like `-DMOTION_WITH_MYSQL:STR=/path/to/lib` or something like that? Please make sure everything that `./configure` supports now, is supported by the new `CMakeLists.txt` instead of just "making the default options work".

Once CMake is merged, I would suggest deleting autotools quickly. It would cost more time to maintain both at once, for a long time.

**Comment by slokhorst** [comment]
The CMake branch has been merged and basic usage should be working. There are a few more point to be looked at:
* Test the CMake build with Travis. Should we test only the minimal build, everything, or both?
* As mentioned in #236 by @tosiara, there seem to be some issues with nonstandard FFmpeg installations. It should be possible to set `PKG_CONFIG_PATH` to point to custom installation directories.
* Take a look at the [remaining unset compiler variables](https://github.com/Motion-Project/motion/blob/master/config.h.in#L18).

I'm currently looking at the two last points. Thoughts on the first point are welcome.

**Comment by Mr-Dave** [comment]
I would like to leave the travis build as is until these CMAKE issues are resolved.

Regarding the second point, I'd like the following workflow to be considered.
1.  At least three different versions of ffmpeg are installed on the computer each in a different directory.  
2.  The base versions from apt are not installed.
3.  Perform tests of a change to Motion under each of the versions of ffmpeg as well as without ffmpeg.  
4.  Now make a change to the code and repeat.  
5.  Install a lib via apt and retest..uninstall lib retest...

The above is my actual workflow and I think that it is important that we consider the developers process in the make system since we are the ones who will use it the most.  My initial try at using CMAKE with the above workflow seemed to require manually removing a lot of files at each variation.

**Comment by jogu** [comment]
> My initial try at using CMAKE with the above workflow seemed to require manually removing a lot of files at each variation.

Just a thought, but for the 'manually removing a lot of files part", how about doing `git clean -fxd` instead - this will remove ALL additional files/directories that aren't in the git repo (so use with care if you've put any test files etc inside the git directory - use `git clean -nxd` to see what it would delete).

**Comment by slokhorst** [comment]
Just removing `CMakeCache.txt` should also do the job. But I agree that it isn't the most elegant solution.

**Comment by Mr-DaveDev** [comment]
I am not going to be able to transition to the cmake system so I'm not sure where this leaves the change.

**Comment by jogu** [comment]
I think we can only build MacOS using Cmake, so for now we're stuck with two build systems then.

I'd see a transition to Cmake as highly desirable if a way can be found to make it work for everyone. Apart from the scenario mentioned above, it seems to be work at least as well as autotools, avoids the hideousness of m4, plus it can do things autotools can't like output a project that can be used with Xcode/ninja/eclipse just like it was a proper project for each of those platforms.
