### ISSUE TITLE
valgrind issues on shutdown with rtsp cameras

### ISSUE THREAD

**Issue by jogu** [Motion-Project/motion#233]
When you shutdown motion in valgrind (tested with some rtsp cameras & ffmpeg 3.1.2), it reports a whole bunch of errors about some of the threads reading invalid memory:

https://gist.github.com/jogu/b378ee9fb303aeb4b633951b4d6d4ced

I noticed we currently use `avcodec_close` in netcam_rtsp_close_context, which according to
https://www.ffmpeg.org/doxygen/3.1/group__lavc__core.html#gaf4daa92361efb3523ef5afeb0b54077f should not be used, but I suspect that is not the problem (although it may explain some of the memory leaks).

Note that to get motion to really work sensibly in my setup under valgrind I had to increase the watchdog timeout:

```
diff --git a/motion.h b/motion.h
index b67add3..59bd73d 100644
--- a/motion.h
+++ b/motion.h
@@ -152,7 +152,7 @@
                                        and then we show a grey image instead
                                      */

-#define WATCHDOG_TMO            30   /* 30 sec max motion_loop interval */
+#define WATCHDOG_TMO            120   /* 30 sec max motion_loop interval */
 #define WATCHDOG_KILL          -60   /* -60 sec grace period before calling thread cancel */
 #define WATCHDOG_OFF          -127   /* Turn off watchdog, used when we wants to quit a thread */
```

**Comment by Mr-Dave** [comment]
This one is strange.  I get basically a clean shutdown.  Only nag it complains about is the <code>mysql_server_init</code> not being freed and leaving 232 bytes possibly lost and 72k bytes still reachable.   The note on not using <code>avcodec_close</code> is seems new for ffmpeg 3.1 and is related to their elimination of <code>avcodec</code>.  Perhaps it is something with the motion options selected?

**Comment by mterzo** [comment]
My code is a bit different than yours is now but i found something similar.

mterzo@43c38fa4f43527cfd6d16febd7c93db6e33ebbab

**Comment by jogu** [comment]
Hi @mterzo - thanks for this! I think that seems like a good change (though I presume it won't help with the valgrind issue I see in the netcam threads) - pthread_detach is (in my opinion) fairly hard to correctly handle. I think someone has tried to fix a similar issue but in a different way in the main tree as I get a conflict if I try and cherry pick your change. I'd be happy to merge a change along these lines.

**Comment by mterzo** [comment]
@jogu just seemed like it was in the same area. It's been over 2 years.

**Comment by tosiara** [comment]
Bumping this one
@jogu , do you still see valgrind issues with the latest trunk?

**Comment by iskunk** [comment]
Hi everyone,

I've been studying this issue, as well as numerous other crashes / Valgrind errors in the RTSP code, and believe I've got a handle on it. Git master still very much has this problem.

The Valgrind log posted by @jogu basically tells the story. The camera thread is deep inside FFmpeg (`avformat_find_stream_info()` in this case), but then the main thread comes along and shuts everything down. As part of that, `netcam->rtsp` gets `free()`d.

But the camera thread is still inside FFmpeg. When it comes up for air via the `netcam_interrupt_rtsp()` callback, the function checks `rtsp->status`, but waitasec, `rtsp` is gone. And thus Valgrind is annoyed.

In general, the problem is that RTSP threads are not shut down very carefully (the code appears to take greater precautions with FTP/wget netcams) and some extra finishing logic is needed.

I have a slew of changes that address this and the other crash modes, and will prepare a pull request. The only bit that's left is some FFmpeg-related memory leakage on shutdown, which I hope can be addressed afterward.

**Comment by iskunk** [comment]
I've found the source of the leakage:
```
     retcd = avformat_open_input(&netcam->rtsp->format_context, netcam->rtsp->path, NULL, &opts);
     if ((retcd < 0) || (netcam->rtsp->interrupted == 1)){
         if (netcam->rtsp->status == RTSP_NOTCONNECTED){
             av_strerror(retcd, errstr, sizeof(errstr));
             MOTION_LOG(ERR, TYPE_NETCAM, NO_ERRNO, "%s: unable to open input(%s): %s", netcam->rtsp->path,errstr);
         }
         av_dict_free(&opts);
         //The format context gets freed upon any error from open_input.
         return retcd;
     }
```

The format context does _not_ get freed if `retcd == 0` and `netcam->rtsp->interrupted == 1`.

With that fixed (and there were a number of other errors of this form, addressed in pull request #368) I am only able to get a very small 16-byte leak that appears to be due to FFmpeg---for the entire Motion run.

**Comment by iskunk** [comment]
I've reported the 16-byte FFmpeg leak here: https://trac.ffmpeg.org/ticket/6334

Also working on getting a couple of Valgrind-fix patches submitted, but _man_ does `ffmpeg-devel` get a lot of traffic...

**Comment by jogu** [comment]
I think this is essentially fixed as far as we know right now (thanks skunk!)
