### ISSUE TITLE
Motion crashes on startup

### ISSUE THREAD

**Issue by krlwlfrt** [Motion-Project/motion#248]
Platform: `Linux alarmpi 4.4.30-1-ARCH #1 Tue Nov 1 21:44:33 MDT 2016 armv6l GNU/Linux`
Hardware: Raspberry Pi Model B+
Version: 4.0.1

Not even `motion -v` works.

**Comment by slokhorst** [comment]
I can confirm the issue on Arch Linux ARM. This happens on a Raspberry Pi 1 (armv6l) but not on a Pi 2 (armv7l). It exits with the message `Illegal instruction (core dumped)`. 

The issue is only there when I use the package from the Arch Linux ARM repository, not there when I compile motion myself. I suspect the package is compiled with an optimization that causes issues on the RPi 1. I'll try to investigate further. @krlwlfrt you can try to compile motion yourself if you want to, to get it running in the meantime.

**Comment by ccrisan** [comment]
I remember seeing Illegal Instruction crashes with motion because of a problematic ffmpeg package.

What I'm saying is that in my case ffmpeg itself was compiled with some non-suitable flags and that was causing motion to crash (even with `-h`). The ffmpeg binary worked fine by itself, though, IIRC.

**Comment by krlwlfrt** [comment]
@slokhorst, yes - the version that I just compiled from current master branch works. So it's probably a problem with the packaging from the arch linux guys.

**Comment by kmihelich** [comment]
The problem is that the configure script is overriding the -march argument provided in the environment CFLAGS with native:
https://github.com/Motion-Project/motion/blob/master/configure.ac#L1033

When ARMv6 packages are built on an ARMv7 host, as is the case for Arch Linux ARM, this causes ARMv7 instructions to be emitted.  When that override is stripped, this problem doesn't exist.  IMHO, the build scripts should not try to be smarter than the distribution package maintainer and supply overriding arguments.

**Comment by jogu** [comment]
@kmihelich That behaviour can be disabled with the --without-optimizecpu option to configure. I suspect Debian probably use that when building their packages.

The configure scripts are (in my opinion) overly complicated these days, and also have a number of bugs. The current thoughts are to try and replace them with a much simple cmake based system - see https://github.com/Motion-Project/motion/pull/236.

**Comment by kmihelich** [comment]
@jogu That flag solves the problem as well, though an "override by default" policy is a pet peeve of mine as this tends to disproportionately affect ARM builds negatively.  Having a flag to disable it is a step above some other projects, however.

Updated packages are available to users so this issue can be closed.

**Comment by slokhorst** [comment]
@kmihelich thanks a lot for your insight and fix!

**Comment by jogu** [comment]
Great, many thanks @kmihelich !

I think it's an oversight that any specified options are overriden; I would hope the new cmake build system behaves better.
