### ISSUE TITLE
Lightswitch enhancement

### ISSUE THREAD

**Issue by zoff99** [Motion-Project/motion#294]
consider enhancing lightswitch option.
now when a lightswitch event is registered, the whole motion event is ignored.
so if light goes on and something moves at the same time, it will be ignored completely.

instead make lightswitch ("new?") ignore more frames
so u need "minimum_motion_frames" of motion to register a motion,
with lightswitch event you need
"minimum_motion_frames" + "lightswtich_ingore_frames" to register as motion.

this way you could ignore 3 frame of the lightswitch event, but if motion continues, you will still get the full event including the lightswitch

**Comment by pcwalden** [comment]
I use lightswitch because of my frequently partly cloudy environment. Clouds moving overhead cause frequent brightening and darkening of the entire image. The lightswitch feature works well to inhibit these events. However, it also causes shadows to appear and disappear, which register as movements. So I think this enhanced lightswitch you are requesting would have to tease these apart more intelligently.

**Comment by tosiara** [comment]
> but if motion continues, you will still get the full event including the lightswitch

Can anyone comment - do we need such behavior (include lightswitch into recording)?

**Comment by richri** [comment]
I support this request ... 

Consider the following situation: The cam at the front door. Next to the door a light with a motion sensor, so that during darkness the light switches on if motion in front of the door.

By now, motion would cosnider the sudden light change as light siwtch and skip this event. But what if a person coming towards the door triggered this event? We would not have a capture of this event although there was considerable motion.

**Comment by tosiara** [comment]
Then disable the lightswitch

On Fri, Feb 23, 2018 at 12:56 PM, Christian Riedel <notifications@github.com

**Comment by zoff99** [comment]
@tosiara thats also not possbile because of a strange bug in motion. some settings are not working as advertised :-(

**Comment by zoff99** [comment]
i want to filter out light on and light off events, yet still capture motion if real motion happens on those events.
the solution is to capture an event if there is at least 10 seconds of continuous motion (less is a light only event).
but that does not work. the settings is not working.

**Comment by Mr-Dave** [comment]
I believe what you have described is not a "strange bug" but different functionality than what is documented.  I invite you to provide pull requests of your proposed changes and resolution to settings that are not working.

**Comment by zoff99** [comment]
@tosiara yes it is.
there is a config for minimum amount of frames of motion. if motion lasts less frames it will be discarded.
and if the motion lasts at least that minimum amount then you get any event (from the start of the motion).
only this setting is not working properly, which i have demonstrated many times.

**Comment by bernd-wechner** [comment]
@tosiara 
With all due respect, and only watching these threads, what is described is very possible, and motion could be fixed to support it. You see there is more to motion than simply changed pixels. And if motion can't detect more than that now it is far from a constraint into the future.

Consider this, that a group of pixels that rapidly change in brightness from dim to near or complete white, that is a fairly trivial scenario to detect and ignore those pixels in a change count. Done.

In fact I have a similar problem using motion outdoors at present. Namely at night I'm casting an eye over a garden watching for mammalian invaders. They, if they come are in the distance and rather small and dim. But my video feed is full of moths and insects flying by the camera, they by comparison are huge and big white blobs. If I can detect these as insects to ignore, it is not only possible, but in this instance a fairly trivial taskf or a piece of software to do so.

So one suggestion is to consider classifying apparent motion, notably looking for pixels that change from dim very suddenly to saturated bright, and offer a config which ignores such changes in motion detection, possibly tuneable (how bright is ignored). This would cover both windows with lights that come on (stationary) and passing insects (moving). If we know that little or nothing we want to detect is super bright these can be ignored safely to great benefit. And for an IR camera at night well placed, well nothing is saturatingly bright unless it's very close or an light source I would guess and these can easily be ignored.

Thoughts?

**Comment by Mr-Dave** [comment]
If you believe that this is a trivial change, then please go forth and provide the pull request with the change.  Likewise for the "strange bug".  I can not see that there is a problem in how the code is working so please go forth on this one as well and find / fix it and provide a pull request.

**Comment by bernd-wechner** [comment]
> If you believe that this is a trivial change, ...

I'm really glad motion is up for PRs on this. I think it's an area of great opportunity for improvement. In fact my use of it has stalled for a moment because of the problem I have with differentiating real motion from lights going on and off in windows and insects flying past real close to the camera (that light up like a light bulb because they are so close and reflecting loads of IR that I presume the camera is transmitting to help light the field up - with IR, at night).

On the flip side, I don't think it a trivial change at all, but a fairly meaningful one. And there ar e at least two distinct effort levels it poses:

1) How much work it would be for someone experienced with image processing and the motion code base.

2) How much work it would be for a newb (me).

The latter is much larger than the former alas. Which is not a road block if said newb has the time and passion to run with it, which alas this one hasn't as yet, though on the cusp. The problem is passion is high, but over-commitment of time is equally high, so I am likely to get as far as forking, and building to set up a dev environment then poking around a bit and then faltering and looking at more pressing jobs as I struggle with getting my head around the hooks into the existing code base to do such a thing ;-). 

Of course give there is already masking code there, that will be the place to look. We're essentially talking an adaptive mask of sorts. We could generate a mask based for example on the brightness delta between two frames. A sudden jump over a threshold from near black to near white might turn the mask on there. And that mask might stay in place again until a reset drop in brightness again. Totally optional thing of course, as predicated on a use case where artificial and undesired light noise comes and goes and is identifiable by its brightness well above any signal we actually want to track (in my case watching for animals - wallabies and rats as it happens).

Just a thought parked here.
