### ISSUE TITLE
Image flip

### ISSUE THREAD

**Issue by asquelt** [Motion-Project/motion#325]
i have a network source, that i need to flip (it's mirrored).
on ccrisan/motioneye/issues/452 i've learned that it should belong to motion.
would it be hard to implement?

**Comment by Mr-Dave** [comment]
This sounds so unusual, I want to be very clear.  I don't think of "flipping" an image as being the same thing as "mirroring" the image.  Flipping the image could refer to rotate which Motion currently does.  So turning the camera upside down, sideways etc is rotate.

The "mirroring" feature that is being requested would be for a situation such as if you have a camera pointed at an **actual** mirror and you are recording the images as shown on the mirror.  The desired change is for the effects of the mirror to be removed so that the resulting images are as if the camera were pointed directly at the object.  

Can you confirm that the enhancement requested is for "mirroring" the image?

If this is the enhancement request, my early assessment is that it would not be a quick easy change.   It is possible that it won't be that difficult but I won't know that until I evaluate how the pixels need to be rearranged to reflect a mirror.

**Comment by asquelt** [comment]
yes, i mean mirroring. actually camera is hanging upside-down but internal software is buggy and flips image while serving mjpegs. i'm not able to fix it in camera. if it's hard to fix, i'd just live with it.

**Comment by unfa** [comment]
That's true. GIMP calls mirroring an image "flipping". Not the same as rotation by 180°.

**Comment by dgomes** [comment]
I'm facing a very similar issue.

I'm currently hooking a "convert -flop" to **on_picture_save** but it only solves the problem of static pictures. I need a similar solution for mjpeg stream.

**Comment by dgomes** [comment]
My pull request adds an extra argument "flip_axis" that does this "rotation".

It basically takes the vertical or horizontal axis and flips the image.

**Comment by asquelt** [comment]
works perfectly for me, thank you! :tada:
