### ISSUE TITLE
Maximum Threshold

### ISSUE THREAD

**Issue by danielchalmers** [Motion-Project/motion#328]
As suggested [here](http://www.lavrsen.dk/foswiki/bin/view/Motion/FeatureRequest2009x05x11x150318) and [here](http://www.lavrsen.dk/foswiki/bin/view/Motion/FeatureRequest2012x10x19x155812), a maximum threshold option would be fantastic.

I have a camera outside and it often detects sunlight changes from clouds and their shadows.  
A maximum threshold would help.

**Comment by tosiara** [comment]
Something like `lightswitch`, but in pixels?
```
# Ignore sudden massive light intensity changes given as a percentage of the picture
# area that changed intensity. Valid range: 0 - 100 , default: 0 = disabled
lightswitch 0
```

**Comment by danielchalmers** [comment]
yes, exactly.

the "threshold" option works as a minimum, "threshold_max" would work as the maximum.

**Comment by tosiara** [comment]
But can you use `lightswitch` somehow for the same purpose?

**Comment by Mr-Dave** [comment]
This request is then to replace the percentage used by <code>lightswitch</code> and instead have that parameter be an absolute number to allow for specifying a maximum value that is more refined than 1%.

**Comment by danielchalmers** [comment]
I actually didn't read @tosiara's first comment right. Sorry about that.  
I'm just looking for a simple max pixels check.  
I've tried `lightswitch` and it doesn't quite work with clouds.

**Comment by Mr-Dave** [comment]
Just to make sure we are on the same page, my comment still stands.  This is because the lightswitch option __is__ already a maximum pixel check.  It is just currently specified as percentage instead of an absolute pixel.

**Comment by danielchalmers** [comment]
`lightswitch` checks for light intensity.  
I'm looking for an option that checks the number of pixels that change per frame like the `threshold` option.  
Like how `threshold` is a minimum, `threshold_max` would be the maximum.

**Comment by Mr-Dave** [comment]
Lightswitch does not check the actual intensity of light.  It check for _changes_ in intensity by looking at the number of pixels that have changed.  [Guide reference](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#lightswitch) .  

Since there seems to be some doubt, here is the actual code that performs the check [here](https://github.com/Motion-Project/motion/blob/master/alg.c#L1267).  As you can see it is comparing the number of pixels that have changed (diff) to image size * (lightswitch parm / 100)  If the number of pixels changed is greater than the threshold, it triggers the lightswitch.

**Comment by danielchalmers** [comment]
Ah. That makes sense.  
A new option won't be necessary then.

Thanks for the help and the info!
