### ISSUE TITLE
Read V4L2 MJPEG video source in a separate thread

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#332]
It looks like RTSP netcam video is being read in a separate thread, while V4L2 is not. Can someone confirm I'm correct?

If it is so, would it be possible to move V4L2 read also to a thread?
The reason is that on low power multi-core systems V4L2 stream read only uses single core. While RTSP uses 2 cores and performs much faster.
Since MJPEG requires a lot of CPU resources on ARM devices, I thought moving it into separate thread would be a great performance boost. The same applies to MJPEG encode for live view

So my question - how much effort would it cost to move all the decodings and encodings into dedicated threads?

**Comment by jogu** [comment]
RTSP is read in a separate thread. It's a bit messy, as the threads aren't actually properly synchronised (the motion thread will run on and motion detect the same frame a second time if a new frame hasn't arrived from the camera).

Does the decode of the V4L2 take a noticeable amount of time?

Really I would like to see us move over to a more 'plugin' type based approach for the cameras so that there is a clear API between the motion loop and the video sources, removing the knowledge of camera type from the core motion loop (the unmerged raspberry pi changes contain a first stab at such an API that didn't look unreasonable to me - https://github.com/jogu/motion/commit/83c4867108e5fd15ae84fd6edadb75ec8560635d is the main commit I think, unfortunately it's mixed in with other changes).

**Comment by tosiara** [comment]
Yes, 1080p MJPEG decoding from V4L2 on low end ARM device will take almost an entire CPU and result in overall performance of about 1fps
We could probably bring the 'plugin' discussion once again (https://github.com/Motion-Project/motion/pull/275#issuecomment-267845317), but I'm not sure how much resources we have at the moment and if it is doable at all. But it would really rock to have API architecture so all new I/O formats are added non-intrusively

**Comment by jogu** [comment]
The plugin API can always be tackled a part at a time as we have the time/inclination/touch the relevant code for that video source (that was how the raspberry pi port was tackling it - I think the only video source that was implemented so far was to read video from a file [for test purposes] or something like that).

**Comment by Mr-Dave** [comment]
Just so you know, I have a branch sitting out there to be pulled in soon that will be implementing V4L2 devices  via the netcam.  The ffmpeg pull is just holding it up a bit since it has some problems that need to be resolved.

**Comment by Mr-Dave** [comment]
I actually have a follow up question on the api / plugin comment.  In the api/plugin world, how would the change for adding in the v4l2:\\\ be implemented differently?  I can easily see better/different  parameters being used but I'm not sure how that would be a "plugin".  

Or is it just somehow restructuring the vid_start, vid_next, vid_close to have them as pointers to functions rather than the current <code>if (cnt->camera_type == CAMERA_TYPE_V4L2) </code> conditions we now have?

Separate compiled shared libraries?  The mjpeg-streamer method?

I just want to make sure I'm following the concept and how it would translate into actual code changes.

**Comment by jogu** [comment]
At this first step all I would see it doing is removing anything that's specific to a camera type from (what was) motion_loop; as you say, using a struct with function pointers for the camera operations as per https://github.com/jogu/motion/commit/83c4867108e5fd15ae84fd6edadb75ec8560635d#diff-9f354372afc20dc6c9a5e5505397bd43


That should in turn make it easier to see how to add a new camera type, as all you have to do is implement that API and register.

I guess we could later add shared libraries etc if we well it useful, but I see just the code cleanups from the first step as worthwhile.

**Comment by tosiara** [comment]
I may be a bit noob in such deeper api architecture, but I like mjpeg_streamer approach, where .so libs represent input

Basicaly, I see motion plugin architecture this way.

![image](https://cloud.githubusercontent.com/assets/3600973/23408052/53760706-fdcf-11e6-8021-f1160df977a7.png)

This way plugins may evolve themselves according to user demand and support and will not needed to touch internal motion loop.

**Comment by jogu** [comment]
It's a fine aim, but it's a lot of work from where we are today, with not a huge tangible benefit.

Separating out the modules into properly independent .so's would mean putting proper APIs in place for handing configuration over to them, stable external APIs for them to access the bits of the core they call, etc. Would be nice to do some day, but I can't see it happening in the short-medium term unless someone is very keen to code it :-)

**Comment by Mr-Dave** [comment]
I am not seeing the benefit either.  Also with the above structure, it would be a massive increase in maintaining. e.g.  How many modules would have to change WHEN ffmpeg decides to change?

**Comment by tosiara** [comment]
Resolved with https://github.com/Motion-Project/motion/commit/eb137c5f5dffc0613a2459a39b855122918a71dc. Needs few tweaking with pixel format selection, but works.
Real motion FPS increased from 20 to 25 fps on low end ARM device 720p MJPEG (just frames decoding and motion detection, no writing) and cpu usage changed from 100% (one core) to 100%+50% (two cores). No sure yet which thread is hitting the limit now: mjpeg decoding or frame analysis. Will investigate later in separate thread
