### ISSUE TITLE
get client-ip on failed log-in attempt

### ISSUE THREAD

**Issue by spyrero** [Motion-Project/motion#348]
Since motion.conf gives the option for stream authentication, I would like to request for a feature of recording/logging failed log-in attempts.

Purpose is to ban (through fail2ban) the IP address that tries to log-in.

It should be a  fairly easy addition in stream.c and webhttpd.c files respectively. 
Motion_log could probably use "STR" argument. Just a thought.

Thank you..

**Comment by tosiara** [comment]
The change would probably need both IPv4 and IPv6 implementation

**Comment by gnanet** [comment]
Prior the stream auth feature was available, i was using nginx as a proxy with http auth to accomplish this, and trough this i have the possibility to log failed attempts. Right now using a new version, but i still rely on the nginx for stream auth. 

But i support the wish itself, because an authentication should be able to log at least "fails" with identification data

**Comment by Mr-Dave** [comment]
Closed via #434
