### ISSUE TITLE
Where is the project lead?

### ISSUE THREAD

**Issue by iskunk** [Motion-Project/motion#374]
According to his GitHub profile page, @Mr-Dave (as well as @Mr-DaveDev) has not been active since March 12. He hasn't responded to an e-mail inquiry I sent a couple weeks ago, and as far as I can tell he hadn't left any indication that he would be away for an extended period of time.

@jogu, @tosiara, do either of you know what's going on? Has anyone here been in touch with him?

**Comment by jogu** [comment]
MrDave has a seasonal job so tends to do most of his motion activity September->December or thereabouts if I remember correctly. My own availability is also erratic; like most people work and family can consume unpredictable amounts of my time.

Unless it's something only MrDave can deal with, I'd recommend (depending what it is) opening an issue here, or posting to one of the mailing lists. In general, we try to discourage people from directly contacting the developers as it quickly becomes too much for one person to deal with.

**Comment by iskunk** [comment]
@jogu, I completely understand that perspective, but five weeks without _any_ activity? Is that typical for him?

If he were posting occasionally to selected issues, then one could say he's postponing greater involvement due to other commitments. But with absolutely no contact, one begins to wonder if some [bus-factor-related incident](https://en.wikipedia.org/wiki/Bus_factor) has happened to him...

(I don't know if only @Mr-Dave can deal with the issues/questions I've found, but you and @tosiara seem to be leaving the code work to him)

**Comment by tosiara** [comment]
@Motion-Project is quite a slow going project and new commits are being merged as soon as MrDave has free time to work on it. We understand and appreciate that
There are other team members who can merge pull requests and have full source access. However we prefer to MrDave to approve pulls, unless it's a obvious small change

That's why you issues https://github.com/Motion-Project/motion/issues/363 https://github.com/Motion-Project/motion/issues/364 https://github.com/Motion-Project/motion/issues/365 https://github.com/Motion-Project/motion/issues/366 are still pending - they are not trivial and require some time to work on and create pulls.
Please be patient, as soon as some of the team members has enough spare time to work on it - we will review your concerns and implement them

**Comment by jogu** [comment]
It's certainly not yet at a point where I'm worried.

The project is setup so that we can carry on making progress without MrDave, that was one thing we fairly careful of after the official project had stalled for a few years before we got it moved over to github. (Admittedly progress is perhaps not fast. There are very few people contributing right now.)

I've not submitted any patches for a while because motion is currently working well enough for me, and the only area I currently have any interest in is direct recording of RTSP streams, which is a major piece of work.

Thanks for the pull requests btw; I had hoped someone else would get the chance to review/merge them, but if they don't I'll try and have a look in due course if they're an area of code that I know well enough. It's fine to ping us on pull requests if you don't get any feedback within a fortnight or so.

**Comment by iskunk** [comment]
Also the way that @Mr-Dave was active on here and then stopped suddenly, as if unexpectedly. That certainly didn't help the bus-factor thinking.

Hopefully it's nothing, and I'm glad that you're not worried. Though if anyone is able to check in with him privately this may be a good time.

(By the way, direct recording of modern video codecs is also something I'm interested in. I don't suppose you have a copy of @Mr-Dave's experimental "passthru" branch? Seems he may have deleted it shortly before disappearing)

The pull requests (not just mine) are piling up! Hope those won't have to wait too long. I was kind of looking forward to discussion beyond those (optimizations to `alg_update_reference_frame()`, architectural changes needed to support IPB frames, etc.)...

**Comment by jogu** [comment]
@iskunk Unfortunately I don't have that branch. I don't believe it included any of the architectural/design type changes needed.

I'm quite up for discussions about IPB frames, although in practise when streaming from netcams we only need to worry about detecting I frames. Probably best to continue that discussion on the passthrough issue. I think we can take quite a lot from how ffmpeg (the command line program) works. But I think we need to make changes to put an interface in between the netcam receive thread and the motion thread so that the netcam thread knows when it can discard an iframe, and the encode/record thread will need more synchronisation with the netcam thread.

**Comment by iskunk** [comment]
@jogu: Nuts! I realize that his code was pretty raw and led to corrupted video, but I did want to see what he was doing with the FFmpeg API. That's still a bit of a black art to me.

I think one of the first things we would need to handle IPB sanely is some kind of GOP data structure that supplements the individual frames. Breaking those apart without hanging on to the original is a big part of the problem...

**Comment by jogu** [comment]
Yeah, the ffmpeg API is pretty scary. At least we don't have to work from first principles; I think ffmpeg.c (and co) already do what we need... it's just a case of understanding how they do it.

I don't understand the 'without hanging onto the original' part - I may have misunderstood, but I think we have to keep the original frame until we know it (and all following non-iframes) are not part of a motion sequence. Once we know they're not needed, we can completely discard.

I think a GOP structure sort of like what we need must already exist in the code used by ffmpeg.c for it to be able to segment videos.

**Comment by iskunk** [comment]
Re "hanging on to the original," what I meant is, hanging on to the original GOP :-)  Once you decode it into individual image pixmaps, you have something that can't be reassembled into compressed video (even if you know which type of frame each image was) without re-encoding.

I don't think our FFmpeg code supports any notion of GOPs, simply because Motion has always worked in the abstract with a series of individual frames and thus has never needed this before. (As far as I can tell, you don't even have to deal with GOPs with the FFmpeg API, just `AVPacket` and `AVFrame` objects.)

(FYI, `AVPacket`s appear to be small chunks of streamed video; in my testing, most of them contained about ~1.5kB of data. I'm guessing multiple `AVPacket`s make up one `AVFrame`, but I'm not sure the meaning of "frame" is the obvious one.)

**Comment by jogu** [comment]
As I understand it, ffmpeg's segment mux is solving this same problem (taking a video stream and splitting it at boundaries such that you end up into independent files essentially at i-frame boundaries so that all the files output are in themselves valid files and there is no overlap or missing sections). e.g. using this command line, which reads from an rtsp stream live:

`ffmpeg -rtsp_transport tcp -i <rtsp url> -vcodec copy -acodec copy -y -map 0 -reset_timestamps 1 -segment_time 8 -f segment output%03d.mkv`

This is really very very similar to solving the exact problem we need to solve in motion; the only bit missing is essentially detecting motion and deciding whether to save the video file or discard it.

As I understand it, this is the code: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/segment.c

I don't actually understand how it works (yet). But it doesn't appear to be worrying too much about GOPs (I haven't actually found the logic that figures out when it is save to start a new video file).

**Comment by iskunk** [comment]
That does look interesting. It's possible that FFmpeg may have solved this problem for us... it would be great if we could just use this (de)muxer via the API rather than have to copy out chunks of their code.

([De]muxing is supposed to be cheap CPU-wise, right? It's the decoding that's expensive, isn't it?)

Did some more reading of docs/code. An `AVFrame` is a decoded video/audio frame, so that's not what we want. A more likely possibility is a ring buffer of `AVPacket`s, but the packets themselves are basically little black boxes---you can't (directly) query whether a packet is an I-frame or the start of an I-frame or whatever.

`AVFrame` does have a handy-dandy field (`enum AVPictureType pict_type`) that tells you what type of frame it is, but you have to send the packets to the codec in order to get a frame, which is presumably expensive. So it seems like we would want a muxer to identify the packets... which I guess the segment muxer is supposed to be capable of.

**Comment by iskunk** [comment]
Okay, some more reading. (De)muxers, apparently, are all about reading and writing specific file formats (or presumably other transport mechanisms), and not about general in-memory manipulation. So we would probably not want to use the segment muxer directly.

But an interesting tidbit in that code---an `AVPacket` has a `flags` field, and that field can have a `AV_PKT_FLAG_KEY` bit set (described as "The packet contains a keyframe"). Also, there is no use of `AVFrame`, and the interaction with the `avcodec_*` API is minimal.

I think that may be enough to start playing around with this. (I'm curious as to how this bit behaves... presumably an I-frame is made up of multiple packets, so do all those packets have the bit set, or just the first one? `printf()` to the rescue!)

On a related note: @Mr-Dave talked about some issues with timing/timestamps:

>  it is related to IPB frames and the timings that occur between the source and the destination. The decoder/encoder makes sure we get and put the appropriate frames at the right time.

> We also can not guarantee that we are always grabbing the frames at the exact same rate that they are being provided by the camera.

I haven't yet been able to grasp what exactly is this problem (I thought we just process the frames as they come in). Did you understand what he was getting at?

**Comment by jogu** [comment]
demuxing is cheap, yes.

I have no idea how the demuxing identifies the i frames, but from my experiments and the documentation it clearly does:

https://www.ffmpeg.org/ffmpeg-formats.html#segment_002c-stream_005fsegment_002c-ssegment

Unfortunately I think (because we need to vary the length of the output files depending on how long the motion lasts, and because we don't know if we can discard the older dater until several seconds after we've received it) that we'll end up duplicating part of the logic in the segment muxer into motion's code.

**Comment by jogu** [comment]
When Mr-Dave was talking about 'We also can not guarantee that we are always grabbing the frames at the exact same rate that they are being provided by the camera.' I believe he's very much talking about the current architecture, where we (in many configurations) decode far more frames than the motion detector thread can process, resulting it in skipping over some frames.

For this passthrough recording to work, I believe we will probably need to add a message from the motion detector thread back to the thread processing the rtsp stream, so that it knows when a GOP has been fully processed, contains no motion, and can hence be discarded.

**Comment by iskunk** [comment]
Most of the segment muxer code appears to deal with UI mechanics: input time/frame lists, output filename formats, generating the M3U file, etc. The actual "where to cut the segment" logic is pretty compact, in `seg_write_packet()`, so there's not much to duplicate in any event.

I thought @Mr-Dave said we can't drop frames... I guess that was about recorded video, as opposed to what goes into the motion detector?

There was also this bit:

> You are right that there are keyframes. (They are the I frames). I did actually think about just grabbing and coding those, but then the timing gets off on capture vs write since the camera will be operating at its own pace of sending keyframes.

That really left me scratching my head... was he really talking about _only_ processing I-frames, for motion detection and recording, and ignoring P/B frames altogether? it seems like the "capture vs. write" issue is the salient part of it, but not if it's just a side effect of only processing I-frames.

As for how to discard GOPs, I was thinking a reference count (incremented by the motion detector while it is searching for motion), since in the future we could conceivably have multiple detection algorithms running in parallel. Then there's making sure that the `pre_capture` period remains covered.

**Comment by Mr-Dave** [comment]
Check the [news](https://github.com/Motion-Project/motion/wiki/News) page.

**Comment by jogu** [comment]
> I thought Mr-Dave said we can't drop frames... I guess that was about recorded video, as opposed to what goes into the motion detector?

Yes, I believe your interpretation is correct. We allow the motion detection to skip some frames. In this new direct recording model, we can't drop any frames coming from the camera (because it would almost certainly result in corrupt video).

> was he really talking about only processing I-frames, for motion detection and recording,

I believe he was thinking of that as an approach to make this work (without making changes to the way motion detection works), but the new way we're talking about here is a much better approach.

I like the sound of your reference counting approach.

**Comment by iskunk** [comment]
Why, hello there @Mr-Dave, we were just talking about you :-)

There was befuddlement at your sudden absence. Dialing down participation is one thing, but I don't usually see someone drop off completely like that unless it's [permanent](http://genecatlow.keenspot.com/).

Anyway, @jogu and I have been doing some work here. If you have any time to spare, what I could really use is not more development muscle, but answers to questions about the code (e.g. issue #366), as well as that "passthru" branch of yours. 

@jogu: Okay, so the frame-dropping (for motion detection) isn't so much of a concern. I want to make sure that I'm not missing some kind of hard problem here, because I'm not really seeing one (aside from deciphering FFmpeg) so far. If you've got a heads-up for anything, I'm all ears.

Will post updates on the other issue, as it's got a bigger crowd...
