### ISSUE TITLE
Overexposed images on Raspberry Pi Camera

### ISSUE THREAD

**Issue by KarlBaumann** [Motion-Project/motion#375]
Hi!

I have RPI with its default 8Mpix camera v2. 
Sometimes camera does not adapt to the changing light when I use it with Motion. Any idea why?
When I rerod videos using raspivid or using Python scripts, everything works fine.
![image](https://cloud.githubusercontent.com/assets/11026930/25284956/e80bfe0e-26b8-11e7-97e0-c3efa74c0922.png)

**Comment by MrReSc** [comment]
I've got the exactly same problem.
![bildschirmfoto vom 2017-05-05 18-59-39](https://cloud.githubusercontent.com/assets/24952268/25755929/2683be6c-31c5-11e7-93e0-bdb0af75b51a.png)

If i take a picture with raspistill it looks like as the following picture:
![bildschirmfoto vom 2017-05-05 19-02-42](https://cloud.githubusercontent.com/assets/24952268/25756029/830322ae-31c5-11e7-820f-f708f34840ab.png)

**Comment by jogu** [comment]
You could try updating the code in the raspicam folder to the latest upstream version, or I believe recent versions of ffmpeg allow use of the raspberry pi camera which may mean it works if you specify the url ffmpeg would expect in the netcam_url setting.

**Comment by MrReSc** [comment]
Thanks for your answer. I think the raspicam should be up to date. Can please tell how the url for ffmpeg should look like? I'm very inexperienced with this stuff.

**Comment by jogu** [comment]
I honestly have no idea. It'd be in the ffmpeg documentation. You may need to upgrade your ffmpeg.

**Comment by yuukiii** [comment]
Here are my settings
![image](https://cloud.githubusercontent.com/assets/14503543/25759401/62f06a64-31a0-11e7-9224-7b1579546cd7.png)

**Comment by MrReSc** [comment]
I've found a solution.
I'm running now mjpg_streamer [https://github.com/jacksonliam/mjpg-streamer](url) and use `netcam_url http://localhost:8080/?action=stream ` in motion.conf. mjpg_streamer handels the Raspberry Pi Camera V2 very well.

**Comment by tosiara** [comment]
Could this be related to auto exposure? I'm not familiar with raspicam, but v4l devices usually have a config param that can be checked using `v4l2-ctl -d /dev/video0 --all`. Does raspicam support runtime param querying?

**Comment by MrReSc** [comment]
Yes, that could be. With mjpg_streamer I set the switch -ex auto which basicaly means auto exposure.
You can find here [https://github.com/jacksonliam/mjpg-streamer/blob/master/mjpg-streamer-experimental/plugins/input_raspicam/README.md](url) more informations.

**Comment by tosiara** [comment]
@jogu is it something motion can do with raspicam? What params are set by default?

**Comment by jogu** [comment]
Default is no parameters:

https://github.com/Motion-Project/motion/blame/master/conf.c#L422

I'd guess you can maybe set the exposure there. But if it's working with raspistill with no parameters it tends to imply our camera code is out of date.

(The raspberry pi code isn't really of any interest to me anymore and it seems no one else is really interested in helping with the coding side of the raspberry pi support unfortunately.)

**Comment by tosiara** [comment]
@MrReSc, can you try to pass auto exposure as config param to motion?

**Comment by MrReSc** [comment]
@tosiara Unfortunately not. I'm running now [MotionEyeOS](https://github.com/ccrisan/motioneyeos) without any problems. They use motion as well. May you can check those config files.

**Comment by tosiara** [comment]
@yuukiii or @KarlBaumann - can someone of you confirm the config param?

**Comment by FaBjE** [comment]
Not sure this is relevant here but since this is quite recent I add this here.

I had a similar issue and try to pass the "fixed exposure" parameter to motion but it doesn't recognize it.
I'm using the latest motioneyeOS with the latest motion version.
Therefore I suspect the included motion for the RPI is build without MMAL support.

I've requested to include it here: https://github.com/ccrisan/motioneyeos/issues/967

**Comment by jogu** [comment]
As I already mentioned, I'm 99% sure that problem is that the mmal camera support code in motion is simply out of date.

Someone could try updating the code in raspicam directory as per the README.txt in that directory.

The raspberry pi code isn't really of any interest to me anymore and it seems no one else is really interested in helping with the coding side of the raspberry pi support unfortunately.

A merge request that fixes this would be most welcome.

**Comment by FaBjE** [comment]
I understood he mmal thing a bit wrong, thanks for your comment at the other issue jogu.
Well, since at least a few people have the same issue, I'm going to take a look at it.

I've done a lot of embedded software development, but this is a first for a "low-level" linux thing. So this might be a steep learning curve.

Wish me luck ;)

**Comment by FaBjE** [comment]
I was able to fix the issue for my setup. It involved a lot of searching/testing But I'm now able to use the camera with motioneye and set the MMAL parameters.

I'm on Raspbian GNU/Linux 8 (jessie)
Kernel: 4.9.29-v7+ 
Raspberry Pi 3, Camera module V2.1 (Not the IR version)
motionEye Version 	0.35.2
Motion Version 	4.0.1

The things I had to do were:

- Create file: /etc/modprobe.d/bcm2835-v4l2.conf
Add: options bcm2835-v4l2 max_video_width=2592 max_video_height=1944
(This changes the point where the GPU goes from video to stills mode (it should not))

- Install latest motion from .deb package found here:
https://github.com/Motion-Project/motion/releases/download/release-4.0.1/pi_jessie_motion_4.0.1-1_armhf.deb

- Set motion binary location for motioneye
For me: "motion_binary /usr/bin/motion" in /etc/motioneye/motioneye.conf

- Set the following "Extra Motion Options" in the webinterface 
mmalcam_control_params -ex night -awb incandescent -co 10 -sa 20
mmalcam_name vc.ril.camera
_Note that you can supply multiple mmal parameters in the one line. Do not add multiple "mmalcam_control_params" because they will be filtered out_

I confirmed the workings by:
- Setting the "image effect negative" mmal parameter and it made the video negative
- The contrast/brightness/saturation controls of motion are not functional (must be set as mmal parameter See: https://www.raspberrypi.org/documentation/raspbian/applications/camera.md)
- the motion log who now shows:
_[0:motion] [NTC] [ALL] conf_load: Processing thread 0 - config file /etc/motioneye/motion.conf
[0:motion] [WRN] [ALL] thread config option deprecated use camera
[0:motion] [NTC] [ALL] config_camera: Processing camera config file thread-1.conf
[0:motion] [NTC] [ALL] motion_startup: Motion 4.0.1 Started
[0:motion] [NTC] [ALL] motion_startup: Logging to syslog
[0:motion] [NTC] [ALL] motion_startup: Using default log type (ALL)
[0:motion] [NTC] [ALL] motion_startup: Using log type (ALL) log level (WRN)
[1:ml1] [ALR] [VID] mmalcam_start: MMAL Camera thread starting... for camera (vc.ril.camera) of 1600 x 1200 at 10 fps
_
So no more "unknown config parameter"
