### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by MustafaCa** [Motion-Project/motion#384]
Bi-directional audio steaming support would make motion the ultimate solution. I hope there is an expert out there who can add this feature. Thanks, Mustafa.

**Comment by MustafaCa** [comment]
Sorry, I meant audio streaming above. Thanks to auto correct in my iPhone.

**Comment by tosiara** [comment]
No audio support yet. But if someone can implement it and provide code chnage for review - you are welcome
For now you can start audio stream manually using ffmpeg and ffserver. I'm doing that with V4L device built-in mic and streaming audio as mpeg2:
`ffmpeg -f alsa -ac 1 -i hw:2,0 http://192.168.0.5:1000/v4l.ffm`

**Comment by tosiara** [comment]
Also see this thread: https://sourceforge.net/p/motion/mailman/motion-user/?viewmonth=201702&viewday=6

**Comment by jogu** [comment]
We've got a ticket for this already: https://github.com/Motion-Project/motion/issues/146

**Comment by MustafaCa** [comment]
Thanks for the replies.

**Comment by locofocos** [comment]
> No audio support yet. But if someone can implement it and provide code chnage for review - you are welcome

Hey Motion team, would do you think this code change would look like architecturally? From my reading, I understand Motion "streams mjpeg and this container does not support audio". If we were going to add streaming audio support to Motion, would that require building out support for a different container that supports video and audio? What do you think would be the most appropriate container- RTSP?

If a new contributor was wanting to step up to contribute this, what would you recommend a software developer look through in order to get familiar with the relevant parts of the codebase? I know software estimates are hard, but do you have any wild guess in regards to how much time it would take to implement this for someone who was familiar with the codebase?

I don't know how much I would be able to contribute, but I'm interested in seeing audio support in Motion. If you want to see the value in adding audio support, look over this thread in motioneyeos: https://github.com/ccrisan/motioneyeos/issues/1322 People buy raspberry pi computers, hook up a USB webcam, and the work your team has done so far does some really amazing things! Your project is a perfect foundation for motioneyeos, and audio streaming is a really common feature among streaming IP cameras.

And of course thanks for all the work you've done on the project so far. I'm using motion to monitor the birth of some new animals on our small farm, and it's provided a really reliable way for me to monitor them without using consumer products that expose the stream over the entire internet. I appreciate what your team has built!

**Comment by Mr-DaveDev** [comment]
First, you need to acknowledge that in the many use cases discussed it is illegal to record audio.  Live Bi-directional is generally fine as I understand it but just recording audio isn't permitted in many countries.

With that disclosure out of the way, I'll indicate that it is contemplated over in [MotionPlus](https://github.com/motion-project/motionplus) but that project is not for under powered computers such as PIs.  With respect to the Motion project, I will not be incorporating audio (even as a PR).  That would have to be something for the next maintainer to maintain.

**Comment by locofocos** [comment]
Got it, thanks for the reply, and all the continued work maintaining it. All the best!

**Comment by mikuloff** [comment]
> many use cases discussed it is illegal to record audio

And exists many legal cases to record audio too. This can't be a reason not to support such a feature, it should be parameterizable, even if it is disabled by default, like preset-record-generic-audio-copy in frigate
