### ISSUE TITLE
Do we have a bug with rtsp cameras since version 270c2fd?

### ISSUE THREAD

**Issue by telemaxx** [Motion-Project/motion#394]
Hi together,
Today i build and installed the latest version (2.June 2017)
With that my old inkstar camera is still working
`netcam_url http://192.168.0.101/videostream.cgi?&resolution=32&rate=15`
but not my rtsp camera. 
`netcam_url rtsp://admin:1234@192.168.0.110/live/ch1`
no live image, only Signal is lost.
restart motion, reboot pi, restart cam.
nothing helped.
so i uninstall the github version and installed the (old)release version 4.0.1-1

Now it is running again.

Someone else, with that problem?

Thanks,
Thomas

**Comment by telemaxx** [comment]
i did some further tests with different git versions:

conection lost since:
270c2fd2e10d9cf828bfedb301b30e192d1605f1

seg fault:
3c0a22ad1ef465ba8a55b4e2f433f5fd369108e5

OK, this Version i use now:
4241d21b7b3075495d7b7e577ba2fe6559a2ebdc

i did not test all versions.

[motion.camera_2.conf.zip](https://github.com/Motion-Project/motion/files/1049433/motion.camera_2.conf.zip)

**Comment by telemaxx** [comment]
i did some further tests with different git versions:

conection lost since:
270c2fd2e10d9cf828bfedb301b30e192d1605f1

seg fault:
3c0a22ad1ef465ba8a55b4e2f433f5fd369108e5

OK, this Version i use now:
4241d21b7b3075495d7b7e577ba2fe6559a2ebdc

i did not test all versions.

**Comment by telemaxx** [comment]
The configuration of the rtsp camera threat.
[motion.camera_2.conf.zip](https://github.com/Motion-Project/motion/files/1049442/motion.camera_2.conf.zip)

**Comment by iskunk** [comment]
Hi @telemaxx,

The segfault at `3c0a22ad` is likely the same as reported by @dimitrystd in issue #377, so that is unlikely to be a concern.

Can you increase your `log_level` to 7, and link here a copy of the Motion log file produced when running the latest master rev?

Also, if you have time, please try the version of Motion in my [development branch](https://github.com/iskunk/motion/tree/iskunk-wip). This has a few fixes that are not yet in the main tree.

**Comment by telemaxx** [comment]
hi  iskunk,
thanks for the responce.

i will try next week and report here.

Is this correct to set loglevel to 7?
/usr/local/bin/motion -n -d 7 -c /home/pi/motion/motion.conf

**Comment by iskunk** [comment]
Thanks @telemaxx, look forward to seeing what you've got.

Yes, `-d 7` can also be used to set the log level.

**Comment by telemaxx** [comment]
here are my logs compressed as zip file.
motion.ok.log --> log from the "old" running version.
motion.bad.log --> log from the latest master version.

i startet this way:
/usr/local/bin/motion.bad -n -c /home/pi/motion/motion.conf.test 2> motion.bad.log > motion.bad.log

what do you think about?

Thanks

[motion.zip](https://github.com/Motion-Project/motion/files/1055865/motion.zip)

**Comment by iskunk** [comment]
Whoaaa! Something very weird is going on with the stream produced by your camera. What is the make and model that you have?

Let's do this: Please get your camera's RTSP stream up and running in VLC. Once you have the right command line for that, add this option: `--sout=file/mp4:telemaxx-stream.mp4`

Instead of displaying the video, VLC will save it to that file. Let it run for a little while, until the file is a good size (no more than 50MB or so), and then post the file somewhere where I can grab it.

By the way, what version of FFmpeg (overall version) are you using? It appears to be older than 2.8...

**Comment by telemaxx** [comment]
I use this Camera:
http://www.wansview.com/works/1080p/indoor/71.html
It delivers 3 streams, i use the middle resultion stream. 640x360
if motion detects motion, it starts an external ffmpeg to record stream 0 in 1080p

no luck with vlc, but ffmpeg should do the same:
/usr/bin/ffmpeg -rtsp_transport tcp -i "rtsp://admin:x1234@192.168.0.110/live/ch1" -c copy -t 30 telemaxx-stream.mp4 >> ffmpeg.log  2>&1

The 30s Video is small, i attach it here.

Doesnt use "motion" use an internal build in ffmpeg? that is motion4.0.1+git4241d21

the external ffmpeg is a static version:
ffmpeg version 3.3.1-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2017 the FFmpeg developers

[ffmpeg.zip](https://github.com/Motion-Project/motion/files/1058128/ffmpeg.zip)

**Comment by telemaxx** [comment]
Now i have also a vlc file:

[telemaxx-stream.zip](https://github.com/Motion-Project/motion/files/1058171/telemaxx-stream.zip)

**Comment by iskunk** [comment]
Thanks @telemaxx. Interestingly, VLC preserved the error, and FFmpeg did not.

I think I see the problem. The stream that the camera is sending is not correctly formed---the very first packet causes FFmpeg to choke and return `AVERROR_INVALIDDATA`. But it seems like if that error is ignored, the later part of the stream will work correctly.

One aspect of my changes that were recently applied to Motion master had to do with error handling, so decoding errors are propagated correctly. It's possible that this stream error was previously being ignored, so Motion worked for you. But once the behavior changed for Motion to bail out, it no longer worked.

Please try this change: Check out the latest Motion master, load up `netcam_rtsp.c` in a text editor, and  search for the call to `avcodec_decode_video2()`. Right after that, add this line:
```
    if (retcd == AVERROR_INVALIDDATA) return 0;
```

(Motion does use FFmpeg internally as it needs to receive and decode the stream itself in order to do motion detection. I'm assuming that Motion is built against an older version of FFmpeg, no later than 2.8. If you are using a newer version of FFmpeg, then you'll need to add the new line after the call to `avcodec_receive_frame()`.)

Compile, and see how well that works for you.

**Comment by telemaxx** [comment]
Hi iskunk,
i have added this line directly two times.
The first short test seem to be ok now.
Now i can see the live view inside the Web UI.

BTW, i have only the statictly linkted ffmpeg3.3 copied into /usr/bin
i use it only to record HD Video when motion was detected. inside my motion.conf i have this line:
`on_event_start "/home/pi/scripts/alarm_ffmpeg.sh  /home/pi/motion/flurcam/%v-%Y%m%d%H%M%S-HD-%$.mkv %$"`

where are this ffmpeg 2.8 libs?
Are there part of the standart raspbian installation?

**Comment by tosiara** [comment]
I think he was talking about this one:
```
[0:motion.bad] [NTC] [ENC] ffmpeg_global_init: ffmpeg libavcodec version 56.1.0 libavformat version 56.1.0
```

**Comment by telemaxx** [comment]
OK now i understand.

in April i used the first time **git**.
i followed the build guide:
`http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Abbreviated_Building`
with the  first cmmand i installed libavcodec and liavformat
`sudo apt-get install libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libavdevice-dev`
Maybe these are outdated now.

i run `apt-get update/upgrade` from time to time. shouldnt that update also the libs?

**Comment by iskunk** [comment]
Yes, the version of FFmpeg that I'm concerned about is the one that Motion links against. When you build Motion, it uses header files in `/usr/include/`, libraries from `/usr/lib/`, etc. so whatever is installed in there is used. (And that's what gets reported in the log file.)

You could upgrade those libs with `apt-get` (provided that they have been updated in the repo that you are using), but there is no need. Motion currently needs to support both the older and newer versions of FFmpeg anyway, so it is okay that you are using an old version. It only means that when you modify the source, you have to modify it in the right place (because the place depends on the version you are using).

So it seems that ignoring `AVERROR_INVALIDDATA` is the correct course of action to allow your camera to work. I'll get a pull request together for this.

Now, this is not ideal, because if the camera just starts sending garbage, then Motion will just eat it indefinitely. At least two better possibilities come to mind:

* Allow up to N such errors before Motion gives up and disconnects (N is chosen to accommodate all known real-world cameras)
* New config directive that enables error tolerance (bailing out on errors remains the default)

But as the non-ideal behavior matches what Motion did previously, I'll just add this as a TODO comment and punt it to a future issue.

**Comment by iskunk** [comment]
@telemaxx, when you have a chance, please give the above pull-request code a try.

This change includes logging of ignored invalid packets. I'm curious to see how many "Ignoring packet" messages you see in your Motion log with normal use. (At present, I am assuming that the camera only sends an invalid packet at the start of the stream and then is well-behaved afterward.)

**Comment by telemaxx** [comment]
i am not familar wit  the git stuff, so i replaced the content of
`netcam_rtsp.c`
with the content of youre pull-request and did the make,make install.
i started the new motion and let it run 4 minutes, incl one motion detection.

seems so, that the error ocours only at the beginning.

`/usr/local/bin/motion -n -c /home/pi/motion/motion.conf.test >> motion.log 2>&1&`

[motion.zip](https://github.com/Motion-Project/motion/files/1065689/motion.zip)

**Comment by telemaxx** [comment]
one more log, this time with incl. the stop sequence

[motion.zip](https://github.com/Motion-Project/motion/files/1065693/motion.zip)

**Comment by iskunk** [comment]
Interesting. It seems like the camera is sending not one, but _four_ invalid packets at the start of the stream. Do you see this consistently? That is, if you start Motion multiple times, is it always four "Ignoring packet" messages that appear in the log?

In any event, the fix is validated. @jogu, @tosiara, please feel free to review and merge this PR when you have a chance.

**Comment by telemaxx** [comment]
Always 4 times that messages at start of the stream. 

In front of this messages 4 times:
`
[0:av1:flurcam] [INF] [ENC] ffmpeg_avcodec_log: A new picture can only be started in the first slice thread
[0:av1:flurcam] [INF] [ENC] ffmpeg_avcodec_log: decode_slice_header error
[0:av1:flurcam] [INF] [ENC] ffmpeg_avcodec_log: no frame!
`
Maybe that is the reason?

**Comment by telemaxx** [comment]
i have just downloaded the last version from git.
it works as expected. 
thanks.

**Comment by iskunk** [comment]
And thanks for the reporting. Yes, while Motion only sees that a given packet contains invalid data, the `ffmpeg_avcodec_log` messages give the gory details of what's going wrong in the decoder.

Interesting that it's always four bad packets. I thought it might have been that the camera was cutting into the midst of an existing stream---seems like the kind of thing a dodgy camera maker would do---but then that would imply that the number of bad packets received at the start would vary, as it would depend on the exact moment you connect to the camera.

Oh well. It's a good data point to have, in any event.
