### ISSUE TITLE
Some informational messages are logged as ALR

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#418]
Such messages appear in systemd journal as errors highlighted in red:

![motion](https://user-images.githubusercontent.com/3600973/28134023-6346cc4e-674a-11e7-9fa1-68d6b7c94d88.png)

Don't know what was the intention, but that looks wrong. These are just informational messages and should go in NTC level

**Comment by iskunk** [comment]
This is something I've noticed as well---just messages not being at the right level in general.

The case I'm most familiar with relates to #363. In `video_v4l2.c`, the `MOTION_LOG()` message to the effect of `got frame before switch timestamp=...` prints a bazillion times due to the issue in that report, at the default log level. Even with that issue addressed, that log message should IMO be at least one higher (INF), since it describes an arguably normal mode of operation.

One other thing that's bothered me: All the `MOTION_LOG()` calls include a `"%s"` that is populated by `__FUNCTION__` in the macro definition. This tends to leave people scratching their heads when they see a call like
```
        MOTION_LOG(ERR, TYPE_VIDEO, NO_ERRNO, "%s: Not a V4L2 device?");
```

with nothing matching up to the `%s`. Why not instead do something like
```
#define MOTION_LOG(x, y, z, format, args...) \
    motion_log(x, y, z, "%s: " format, __FUNCTION__, ##args)

/* ... */

        MOTION_LOG(ERR, TYPE_VIDEO, NO_ERRNO, "Not a V4L2 device?");
```

?

**Comment by tosiara** [comment]
I agree, absolutely no need to carry that %s in every call. Let me grep the
code and create a pull request

**Comment by tosiara** [comment]
Done, PR updated

**Comment by tosiara** [comment]
@iskunk if you have time, can you please take a look if the implementation is exactly what you proposed. Thanks

**Comment by iskunk** [comment]
Hi @tosiara, I looked over the changes. The only bit I found that looked off was in CODE_STANDARD, where the change was applied to a `syslog()` call. Otherwise, yep, that's the idea :-)

**Comment by tosiara** [comment]
Thanks!
Yeah, I will put "%s" back in the CODE_STANDARD, that's not a MOTION_LOG macros case

**Comment by tosiara** [comment]
Closed via https://github.com/Motion-Project/motion/pull/426
