### ISSUE TITLE
Lightswitch can't understand how it work

### ISSUE THREAD

**Issue by juxorevo** [Motion-Project/motion#429]
1. version [4.0.1]: 
2. installed as a package or compiled from sources [deb]: 
3. standalone or part of third party [motion]: 
4. video stream source [RTSP]: 
5. hardware [ARM (Rasp)]: 
6. operating system [Debian Rasp version]: 

Hello everyone, 

If I have a lot of brightness I have to increase the percentage of lightswitch value or reduce it?

(Motion is a very perfect and usefull project !)

Regards

**Comment by genius3000** [comment]
That depends on what you mean by "have a lot of brightness".

If you mean __constantly bright__:  
- (Consider reducing brightness unless you want this)  
- You'd want to reduce 'lightswitch' if the change of light is small.

If you mean __lot of brightness in a sudden change__:  
- This is what 'lightswitch' is meant to handle, estimate the percentage of the picture that is affected by the sudden change of light and start with that. You could use setup mode to help test things.

**Comment by juxorevo** [comment]
I'm gone test it.

**Comment by Mr-Dave** [comment]
Closing this as it is a use question rather than a issue with respect to the code.  Please make sure to read the [guide](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#lightswitch) and also consider joining the [mailing list](https://sourceforge.net/projects/motion/lists/motion-user)

**Comment by juxorevo** [comment]
How sorry for the issue. I have openned it because, i haven't undestand the guide.

Thank you for your help.

regards
