### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by jony0008** [Motion-Project/motion#440]
Would be great to have motion in different languages. I can recommend Crowdin or Weblate for managing the translations.

**Comment by Mr-Dave** [comment]
At least for Crowdin, it appears to be a pay/subscriber service.  As far as I know, none of the project developers receive any monetary gain from this project so translations would need to be via a free service or provided by the community.  

For Weblate, if you have a demo of how it would work with this project, I can review it.

**Comment by Mr-Dave** [comment]
Closing this issue as I do not see how this could be effectively accomplished within the project.  Any translations implemented within the project would be "at best" as good as what a user would get using their own preferred online translation tool.

**Comment by Mr-Dave** [comment]
Reopening this issue in light of recent commit that includes limited translations.  

Help is requested to provide the following:
1.  Validation that the locale is properly being captured and revising the web interface language.

2. Validation of translations are correct for the following which are in the current master branch.
- [ ] Spanish
- [ ] French
- [ ] Dutch
- [ ] lithuanian  

2.  Add other languages into translate.c

3.  Translations for configuration options.
  Translations must be short and use underscores instead of spaces. 
  The current use is these will be listed on the web interface.
  May be used in future for specification in configuration file(s)

It is still not currently contemplated that the guide or manual would be translated.

**Comment by tosiara** [comment]
Can you please remind me how do I contribute to translations?

**Comment by tosiara** [comment]
Is it just a PR needed for one file: https://github.com/Motion-Project/motion/blob/master/translate.c ?

**Comment by Mr-Dave** [comment]
That is correct.  For items not currently translated, add additional rows to that file.  The format for the new rows is the two digit locale language code, the english word or phrase and then the corresponding translated word/phrase.

For incorrect translations simply find the row with the incorrect translation change the translated word. 

Note that my sample translations for the `setup_mode` option are not good.  What we really want for the translation of the option is a alternative configuration name in the foreign language.  This way a subsequent pull request will be able to read a configuration file that has those options and translate those specifications into english for use in the program.

**Comment by Mr-Dave** [comment]
As cited in PR #669 , the existing translation method may not be able to be packaged  and distributed on all platforms (non-ascii characters in the code).  The `gettext` library is a possible option but upon review, it would involve a significant amount of changes to the build system as well as the code.  

I would ask the audience whether they see any issue in having a separate configuration file  with the translations.  Essentially it would be the equivalent of what was in the translate.c but instead of being in the code, it would be in a optional conf file.

**Comment by Mr-Dave** [comment]
The revisions necessary for implementing translations have been pushed into the master branch.  Instructions for how to add translations for all messages is included in the build [guide](https://rawgit.com/Motion-Project/motion/master/motion_build.html#Translations)
