### ISSUE TITLE
CMAKE drop

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#460]
Let's discuss whether we want to keep two build systems or not
MrDave's quote https://github.com/Motion-Project/motion/pull/444#issuecomment-320669274 :

> I don't think this will be any surprise but I think it has to be dropped and cut out of the code base before the next release. Continuing to include it just causes confusion and extra work. It doesn't provide the functionality I need and the work arounds are terrible and accidentally resulted in my losing hours of work twice. It seems to expect developers to write flawless code and fix every warning perfectly without ever going back.

IMO, cmake has not been maintained since it was added. And I tend to agree with MrDave. I can only offer an intermediate solution to move all cmake files to a branch and keep there for enthusiasts

**Comment by iskunk** [comment]
The main value of CMake, in my view, is facilitating native IDE builds on Windows and MacOS X.

CMake can generate a solution file for Visual Studio, an Xcode project for Mac, and the equivalent for many other less-popular IDEs (Borland et al.).

You can still do Windows builds using Autotools if you use the MinGW toolchain (whether cross-compiling from Linux, or running on Windows itself). But if you're a typical Windows developer with some form of Visual Studio (probably the free Express version) installed, and that's all you know, it's going to be less straightforward. (I recall it's possible to do with [hacks](https://github.com/swig/cccl), but I don't think CL.EXE has ever been supported directly.)

For sure, a CMake build system is better than hand-maintained IDE project files. This is especially the case with Visual Studio projects, because those are tied to the version of the IDE. Backwards compatibility for VS projects is non-existent, and forwards-compatibility is dodgy at best.

MacOS X is less of an issue vis-a-vis Autotools, because the underlying toolchain is already all Unix. Some folks would still probably want Xcode projects, however.

If you're going to have only one build system, then my personal preference would be to keep Autotools. Other projects have gone CMake-only, especially if they are more popular on Windows. But the CMake build interface is nowhere near as standardized/familiar as Autotools, and for that reason I always groan when I have to deal with a project that uses something different.

Now, if there is anything specific that is needed here of CMake, I'd like to try to offer a solution. I'm pretty experienced with this tool, because I've applied it professionally to get a large Autotools-based project building on Windows. I already have some tweaks to `CMakeLists.txt` in my `iskunk-wip` branch, even, to address some problems I found in the course of the passthru work.

**Comment by jogu** [comment]
My thoughts on cmake are:

Pros:
- I can work in Xcode and things actually work properly
- Our cmake configuration is a hell of a lot simpler than our auto tools ones (I've tried to fix things in our auto tools in the past - between archaic m4 and the fact that whoever wrote a good chunk of our autotools config had some serious misunderstandings about how it worked I just gave up, everytime I fixed something it just revealed that another part was working by luck. I appreciate our auto tool setup may well be better these days, but it's still an archaic and error prone system IMHO. :-) )

That said I'm struggling to find much time to work on motion these days :-(

I've worked with a number of people that have taken (closed source in this case) projects cmake only. They didn't regret it.

I'm not sure either of the flaws MrDave mentions are something inherent in cmake; I presume they're likely just something in our configuration that's fixable.

**Comment by Mr-Dave** [comment]
The issue that drove me to this position is really related to the fact that there is no "clean" or "force rebuild" functionality.  From what I've researched and been told on the original issue introducing CMAKE is that it is inherent to CMAKE.  The answers from the other community boards are generally  along the lines of  "You don't need that" or here is a script to wrap around it.   

The particular workflow was documented in our other issue with its introduction whereby we need to develop and test things like five different versions of ffmpeg and make sure that they are all working.  To do this you need to effectively clean the tree or the out of source location each time which is manual.  We also need to clean to re-trigger seeing compiler warnings and work through them.  

If you have perfect code or are a end user only executing it once, then it is great and you can port it everywhere.  If you are executing it many many times trying to resolve libav vs ffmpeg and versions 2.6 to 3.2 then it is a very real impediment manually cleaning after each trial.  And of course since this cleaning process is manual, it can lead to "accidents" which wipe out hours and hours of work.

Of course that is only my workflow, we should also consider that changing to it would trigger extra work for everyone else that has packaged and deployed Motion.  

Finally, keeping one build system for development and another for release is really not a good use of resources.  There very limited resources to begin with and splitting them maintaining two build systems is inefficient.

**Comment by iskunk** [comment]
@Mr-Dave: CMake does provide a `make clean` target, but if you're looking for `make distclean` and the like, then yes, that's not there. A big part of the difference with Autotools is that CMake by necessity relies much more heavily on the practice of building outside the source tree, due to the variety of build systems that it supports.

(After all, how would you implement the equivalent of `distclean` or `maintainer-clean` in a Visual Studio project? A target that, when run, deletes the project file itself and all generated source files? That would just cause the IDE to choke, if file locking doesn't prevent deletion of the open project file altogether.)

I don't ding CMake too hard on this, however, because out-of-source builds is the better approach in any event. You can do things like have multiple build trees, all with different configurations, all hanging off the same source tree. The source tree can be read-only, even (e.g. if it were on a R/O NFS mount).

As for testing all these different versions of FFmpeg... I'd point out, it's a perfectly respectable compromise to say that the CMake build _only_ supports FFmpeg 3.2+ or the like. You're not going to have Windows users complaining, "but my Windows distro only comes with FFmpeg 2.8!" No, if they're building the thing, they have to get FFmpeg themselves. So there's not much excuse for them to download anything but the latest version.

**Comment by Mr-Dave** [comment]
On the testing and versions comment of ffmpeg, we package [releases](https://github.com/Motion-Project/motion/releases) for the active versions of the distros.  This means testing and validating for 14.04, 16.04, 17.04, 17.10, 18.04, Jessie, Stretch, Raspian, FreeBSD, etc.  

I would certainly agree it would be MUCH easier to just support the latest ffmpeg release but as of now, that seems like a unreasonable expectation.  I think only after 16.04 hits EOL and users have a functional application via apt could the project move to only supporting current versions.  

I guess I'll leave it as I'm pretty firm on not using CMAKE for anything I do.  It stung me a couple of times and there are MANY more pressing issues with the project that need to be addressed.

**Comment by iskunk** [comment]
My proposal was, support all the various FFmpeg releases in Autotools, but only the latest in CMake. The main value of having CMake is for Windows builds anyway, where the "support various distros" situation doesn't exist in the first place.
