### ISSUE TITLE
Motion 4.0.1 does not have settings for mmalcam in configuration file

### ISSUE THREAD

**Issue by kilojarek** [Motion-Project/motion#470]
Stock version of Motion 4.0.1 installed on Raspberry Pi Zero with Jesse does not allow for configuration of Picamera (via the `mmalcam_name` parameter, even though the manual implies it is present in the default configuration file (section "Basic Setup" in [https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/release-4.0.1/motion_guide.html#Command_Line_Options](https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/release-4.0.1/motion_guide.html#Command_Line_Options). 
Manual also implies that the default installation includes file `/etc/motion/motion-dist.conf` and it doesn't (section "Installing with apt"). The only file there is `/etc/motion/motion.conf`.

**Comment by Mr-Dave** [comment]
The appropriate section of guide is [here](https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/release-4.0.1/motion_guide.html#Options_Raspi_Cameras)  With respect to the name of the file, the debian packagers renamed the <code>/etc/motion/motion-dist.conf</code> to <code>/etc/motion/motion.conf</code> in order to assist users since this is a required step in the setup.

**Comment by kilojarek** [comment]
Yes, the instructions are in the manual, but the `motion.conf` does not have the settings that the manual mentions. Ie I cannot set the `mmalcam_name` parameter in `motion.conf` because it is not there.

**Comment by genius3000** [comment]
Does it not work to just add the needed parameter(s) to motion.conf? Motion will log warnings if the parameters are unknown to it.

**Comment by Mr-Dave** [comment]
If the option is not already listed in the configuration file, it is likely that the version installed is not the 4.0.1 that was indicated in the OP.  Since there is no "stock" install method, my guess at how motion was installed was via the apt packages.  If this is the case, the apt package for Jessie did not include 4.0.1.  It was the version before mmal was added.  To get the 4.0.1 version, it would be necessary to either install via the deb package or upgrade to stretch.  The version should be validated by typing <code>motion -v</code>.  Also, should validate that version number corresponds with the configuration file which includes the version number at the top.

**Comment by kilojarek** [comment]
Ah, you're right. My motion (installed with apt) is 3.2.12... I will upgrade to Stretch and let you know in a couple of weeks.

**Comment by Mr-Dave** [comment]
Closing issue.  Note that when upgrading, you may want to rename the existing motion.conf file or uninstall motion completely so that there aren't any conflicts of the versions.
