### ISSUE TITLE
Problem running motion with mysql libraries even when configured for sqlite3

### ISSUE THREAD

**Issue by antoinecarme** [Motion-Project/motion#490]
Using motion 4.0.1 on debian. I have the following error message when running motion:

```
./motion 
motion: error while loading shared libraries: libmariadbclient.so.18: cannot open shared object file: No such file or directory
```

I am not sure I can fix this error as a normal user (probably a badly configured mysql/mariadb).

I really don't want to use mysql for motion (specified sqlite3 in the motion.conf file).

Looking at the source code, motion tries loading the mysql library every time even if the configuration does not use it, which is not normal.

Your help is welcome, I only want to play with motion and sqlite3 ... and mysql is blocking the situation here.

Thanks in advance

**Comment by Mr-Dave** [comment]
We will need more details on this in order to determine cause and resolution.  Can you provide the items described in the [contributing guide](https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md)?  (Logs, configs, specifically how motion was installed, debian version, etc)

Additionally for your situation, can you indicate whether any packages were removed after Motion was installed.

**Comment by Mr-DaveDev** [comment]
Closing.
