### ISSUE TITLE
Change of mask_file via webserver not working

### ISSUE THREAD

**Issue by cimba007** [Motion-Project/motion#515]
1. version [x.y.z, hash, other]:
**motion/stable,now 4.0-1 armhf  [installiert]**
2. installed as a package or compiled from sources [deb, rpm, git, other]:
 **package**
3. standalone or part of third party [motion, MotionEyeOS, other]: 
**standalong motion (apt-get)**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:
 **raspicam v1, v4l**
5. hardware [x86, ARM, other]:
 **raspberry pi 1 B+, raspberry pi camera V1**
6. operating system [Linux (which), FreeBSD, other]:
 **debian stretch**

Changing the mask_file via integrated webserver is not working. mask_file is only accepted if defined in config-file /etc/motion/motion.conf

**Comment by genius3000** [comment]
As noted by the referenced PR, the current `master` has a bad config write bug. With that fixed, I am able to set `mask_file` in the WebUI and write the config successfully, including the changed `mask_file`.  
I'm not sure if a change since the 4.0 release and current `master` would have fixed a bug causing your issue or not. I made quite a few changes to the config system in there, but nothing directly related to `mask_file`.

Can you confirm you are also writing the config, not just changing the value? A snippet of the log (motion start, open WebUI, change setting, write config, stop motion) would be great as well. Please review the [Wiki - Privacy article](https://github.com/Motion-Project/motion/wiki/Privacy) and use a Gist instead of pasting to this thread.

**Comment by cimba007** [comment]
To be precise .. 

If I change some parameters like brightness in the WebUI that is working. Other values like changing threshold are working too (although they are not persistent until I restart but this is fine as I just want to try out the best parameter).

The log-file generated with "motion -d 9" sadly does not give many information regarding the setting of the mask_file via WebUI

```
[1:ml1] [DBG] [VID] [Oct 15 15:52:14] v4l2_next: 1) vid_source->pframe 3
[1:ml1] [DBG] [VID] [Oct 15 15:52:14] v4l2_next: 2) vid_source->pframe 3
[1:ml1] [DBG] [VID] [Oct 15 15:52:14] v4l2_next: 3) vid_source->pframe 0 vid_source->buf.index 0
[1:ml1] [DBG] [VID] [Oct 15 15:52:14] v4l2_next: vid_source->buf.bytesused 460800
[1:ml1] [DBG] [VID] [Oct 15 15:52:14] v4l2_next: the_buffer index 0 Address (b067e000)
[0:web_control] [NTC] [STR] [Oct 15 15:52:14] httpd_run: motion-httpd - Read from client
[1:ml1] [DBG] [VID] [Oct 15 15:52:15] v4l2_next: 1) vid_source->pframe 0
[1:ml1] [DBG] [VID] [Oct 15 15:52:15] v4l2_next: 2) vid_source->pframe 0
[1:ml1] [DBG] [VID] [Oct 15 15:52:15] v4l2_next: 3) vid_source->pframe 1 vid_source->buf.index 1
[1:ml1] [DBG] [VID] [Oct 15 15:52:15] v4l2_next: vid_source->buf.bytesused 460800
[1:ml1] [DBG] [VID] [Oct 15 15:52:15] v4l2_next: the_buffer index 1 Address (b060d000)
```

What is the best way to generate a more "verbose" output of the web_control?

**Comment by Mr-Dave** [comment]
I do not believe additional output is required.  The mask files can not be changed while Motion is running.  There are few other parameters that are this way as well that need to be cleaned up.

**Comment by cimba007** [comment]
Okay, nice to know ;-) Maybe these options should be marked on the WebUI or removed alltogether

**Comment by genius3000** [comment]
Ah my mistake, I was reading the issue as the config write (from the WebUI) was failing to write the new value of `mask_file`.  
I would say the options should remain available on the WebUI, as you can change and write the config file from there, then restart to apply the changes. Having them marked in some way isn't a bad idea. What were your thoughts @Mr-Dave re: the parameters that need cleaned up?

**Comment by cimba007** [comment]
Partly my mistake too. I didn't even know you can save the changes directly to the config file. A small (* does not apply until saved to config and next reload) might have helped me in this case ;-)

**Comment by Mr-Dave** [comment]
My initial thoughts are that we'd somehow tag each configuration option and whether to include it in the web interface.  I'm not really a fan of having all the configuration options exposed and would generally opt for only allowing for adjustment of things like frame_rate or threshold.  Items such as the masks, "on" commands, urls, passwords, heigh/width, etc should really require going directly to the configuration file rather than a webui.

**Comment by genius3000** [comment]
From a security/privacy and personal view (I don't typically enable the WebUI), I'm on board with having a minimal number of options exposed to the WebUI. I just have to wonder how many users currently rely on the WebUI for most/all config changes right now.
It would be a seemingly large change but the best way about this is likely another flag in the config_params struct for whether to expose or not. I believe checking that in the WebUI code should be simple enough as well.

**Comment by Mr-Dave** [comment]
PR #530 should close this issue.  There is now a configuration option which allows the user to specify which options are available via the web interface.  As specified in the new documentation, options which are specified at the advanced and expert levels would require a restart of Motion to become effective.  Options at the limited level are the ones that can affect the running parameters.   Finally there is a level of none which should address security concerns by removing all parameter editing via the webcontrol.
