### ISSUE TITLE
Doxygen: Yay or Nay?

### ISSUE THREAD

**Issue by genius3000** [Motion-Project/motion#520]
I gave Doxygen a run on the motion code base with a generic config and no modifications to the code comments, it gave a half-decent result.
I've got it available for viewing on my server: https://g3k.solutions/motion-doxygen/
Are we interested in having this? I honestly haven't looked much into it yet but it would likely require more/changed commenting in the header files to get a more detailed result.

**Comment by Mr-Dave** [comment]
I'm on the Nay side at this point.   Primarily from a "Is there resources to maintain this" point of view and "Would it assist in the development process for me or others" .  

As most know, the resources are very limited and as I looked at the pages, I tried to image "Would I use these pages as I was contemplating/working changes" and my answer was "No.  I'd open my code editor".  

The other use would be for new developers and from what I've observed they also seem to just get into the code and not review documentation that is external to the code itself.

**Comment by iskunk** [comment]
Code documentation is good, though I'm not sure what the value is of the highly structured documentation that Doxygen provides to a project that has developed "organically" like Motion. It's already recognized that the whole thing sorely needs re-architecturing anyway, so such bookkeeping would probably not even be all that future-proof anyway..

Where it's at right now, what would probably be most helpful are just comments explaining all the weird and idiosyncratic bits in there so that a new developer will have an easier time finding their way around...
