### ISSUE TITLE
raspbian permissions

### ISSUE THREAD

**Issue by Thijxx** [Motion-Project/motion#524]
1. v4.0
2. raspbian stretch
3. standalone
5. hardware [x86, ARM, other]: pi3
6. operating system [Linux (which), FreeBSD, other]: raspbian

This issue seems to be an issue still:
https://github.com/Motion-Project/motion/issues/35

Motion creates files with inconvenient permissions and there is no config setting to change this.
It is `motion:motion` with `rw_r__r__`

**Comment by damluk** [comment]
Which permissions should those files have? The Debian packaging is not part of this repository, so maybe this issue should be reported to the Debian maintainers. A umask could be easily added as a configurable parameter to start-stop-daemon.

**Comment by Thijxx** [comment]
It would be nice to have write permissions for the group but a UMASK setting sounds better. I'm a bit lost in the Raspbian/Ubuntu/Debian ferris wheel but I'll try to locate the package maintainers, thanks.

**Comment by Mr-Dave** [comment]
A copy of the packaging is available [here](https://github.com/Motion-Project/motion-packaging) where you can propose a change for the project deb packages.  Changes implemented there can be pointed out to the Debian packager whenever we release the next version.

**Comment by Thijxx** [comment]
Continued here:
https://github.com/Motion-Project/motion-packaging/issues/2

**Comment by johnelliott** [comment]
I had to modify permissions after installing on a raspberry pi 3 and zero wireless on stretch with apt. I could never duplicate the solution. I can only see log output when running as the current pi user, and when I try to run the systemd service I cannot see what is going wrong because I don't get any output. I've tried various combinations of permissions and groups, but I can't get the software to run. It's a shame because most other packages 'just work'.
