### ISSUE TITLE
Run a script on start

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#551]
Running a script on motion start, main loop start or watchdog restart would be a very useful feature. For example, for those who needs custom UVC V4L params that get reset to default when motion opens the device.

I thought that `on_camera_found` is executed on start, but it isn't
So, having a new option `on_process_start` or `on_main_start` would be great

Leaving this for a few weeks to discuss pros and cons

**Comment by Mr-Dave** [comment]
The thought is OK but the problem would be that Motion would have to wait for it to finish before continuing.

**Comment by tosiara** [comment]
How if current script execute implemented, ex, `on event`? Is it a fork or is it a lock waiting for command to complete?

**Comment by Mr-Dave** [comment]
It is a [fork. ](https://github.com/Motion-Project/motion/blob/ccbe2f59272b029b49a106224e8bde7114da0814/event.c#L65) so in order to be effective for running the v4l2 commands, there would have to be another parameter to indicate whether to wait or not.  Better to just indicate that these type of startup / shutdown scripts be executed outside of the application in custom user scripts.
