### ISSUE TITLE
Is it possible to read local file and write the output over the streamed images?

### ISSUE THREAD

**Issue by adrianharabula** [Motion-Project/motion#557]
Hello, I have a temperature sensor on raspberry pi, is there a way to write over the streamed image the temperature (it is read from a file)?

Currently I can only put a hardcoded string with _text_left_ option in config file.

Thanks.

1. version [x.y.z, hash, other]: 4.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: apt-get install
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]:  usb
5. hardware [x86, ARM, other]: arm
6. operating system [Linux (which), FreeBSD, other]: raspbian

**Comment by tosiara** [comment]
No, there is no way to display external data
If you wish to experiment you can implement your own template here: https://github.com/Motion-Project/motion/blob/master/motion.c#L3527, like `{temperature}`

**Comment by Mr-Dave** [comment]
I have thought a bit about this one and do not think that it would be a good idea to have Motion start to try to grab items externally for inclusion in the image.  i.e. Pull a value from somewhere.  It is better to have an external process push the desired item to Motion via the URL interface options.  

The reason for my thinking on this is that Motion could be grabbing pictures at 30fps or faster and we can not be sure that whatever is being called to provide the value can respond that quickly.  If what is providing the value can not respond with the value that quickly, then the captures slow down and all sorts of other items get impacted.  (Note that while in this particular situation the temp "may" be able to meet the timely response criteria, we must think about whether it would be true for all users.)  

Instead, it would seem better to have a external script that calls the function to get the temp (or whatever else is desired) at the update frequency that the user wants, and then uses the Motion web update to change the text_left/text_right to include the value.  This way the user could set it up so that the temp gets update once every 5 minutes rather than having Motion try to update the temp 30 times per second.

**Comment by tosiara** [comment]
I agree. Supplying text values through http api call and keep values in memory would be a better way
