### ISSUE TITLE
Variable FPS bug

### ISSUE THREAD

**Issue by tosiara** [Motion-Project/motion#56]
(cross post from mail list)

Hi,

I have seen this bug for quite long time, but now finally created
proof of concept.

The issue is how motion deals with variable frame rate. Depending on
the amount of light a web cam changes FPS: more light - more frames
per second.

When real frame rate increases - motion generates "slow" movie. For
example, motion started movie as 7 fps, but then camera started
sending 30 fps - you will have "slowmotion" effect.

When real frame rate decreases - motion starts filling "pauses" into
movie: copying last second's frame N-times.

Please see examples: (download original MP4, don't use flash player)

"Slowmotion" - https://yadi.sk/i/hnsMAPhTeKpH9
"Lags" - https://yadi.sk/i/4cnHPQAyeKpKj

Config: http://pastebin.com/FUViNzQt
Uses extpipe x264 (compiled with gpac)
Compiled latest "master" branch of Mr-Dave - https://github.com/Mr-Dave/motion

To reproduce "slowmotion", close web camera lens using your finger -
it will drop to the lowest framerate. Start motion, wait for 10
seconds and start generating movements - motion will begin writing a
movie at 7 fps. Then use flashlight to bring more light into web cam
lens - camera starts giving maximum frame rate.

To reproduce "lags" do vice versa. Turn on flashlight, camera will
switch to highest frame rate. Start motion and generate movements -
motion starts movie at 30 fps. Now turn flashlight off - camera drops
frame rate to lover (15 in my case).

Any ideas how we could fix that?

Thanks

**Comment by Mr-Dave** [comment]
I did not see anything simple to resolve this.  There are many interactions going on with the filling to hit a FPS rate processing, the PTS / DTS set within the movie stream, as well as the configuration FPS vs the average FPS.  I probably won't be able to look deeper into this for many many months due to other commitments.

**Comment by Mr-Dave** [comment]
Many months have now passed and I have still not determined whether this is even a problem that "can" be fixed.  We set the FPS as the very first thing in creating the movie.  If the camera changes that FPS while the frames are being added, I'm not seeing how to change it.   We'd have to stop that movie and create another at the lower or higher FPS. (Which wouldn't be practical).    It seems like the only option would be to set the camera to feed at the "dark" rate even when the lights are on or change the requested FPS in motion to the "dark" rate so that it will record at that level just in case the lights go off during the creation of a movie.

**Comment by Mr-Dave** [comment]
Do you have more details on why this was classified as a bug or how my comments would be addressed?

**Comment by tosiara** [comment]
I have been able to reproduce this issue and record two videos. Both videos does not look as expected. That's why I believe it's a bug rather that enhancement

This is not trivial to explain, but I think motion has to distribute frames across 1 second if fps has decreased or drop frames if fps is exceeding. But dropping frames is probably not a good idea

Maybe we should always have 30 fps video files hardcoded no matter which fps the camera provides. And then just duplicate frames if fps is lower to get smooth video. Also, advantage of fixed fps is that you can later concatenate video files.
But I agree this is not something trivial
