### ISSUE TITLE
rtsp_uses_tcp on gets ignored

### ISSUE THREAD

**Issue by cantonfe** [Motion-Project/motion#588]
1. version [x.y.z, hash, other]: 4.1.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtsp
5. hardware [x86, ARM, other]: armhf
6. operating system [Linux (which), FreeBSD, other]: raspbian stretch

I am trying to monitor a Uniti camera. I can connect to it via rtsp. Motion seems to connect to it and works fine except for image quality. The first seconds look fine and afterwards the lower part of the image looks blurry. 
If I try to connect to the camera via ffplay 
`ffplay rtsp://some.ip -rtsp_transport tcp `
looks fine and no errors, but if I do 
`ffplay rtsp://some.ip  `
the image is fine on the top (about half) and then the last line is just reproduced until the end of the image (they look like bars). And I get errors:
max delay reached. need to consume packet=0/0   
RTP: missed 101 packets
error while decoding MB 11 36, bytestream -20   
concealing 3878 DC, 3878 AC, 3878 MV errors in I frame_

which I believe are quite common when ffmpeg is using udp. 

My configuration file /etc/motion/motion.conf has the line `rtsp_uses_tcp on` but it does not seem to have an effect. 

On the log for motion (level 9) I get lots of 
[3:nc3] [INF] [ENC] [Dec 25 20:45:46] ffmpeg_avcodec_log: error while decoding MB 103 26, bytestream -6

![01-20171225182638-01](https://user-images.githubusercontent.com/24914247/34342643-8b686f86-e9b6-11e7-89f2-425364a519ed.jpg)

![02-20171225183113-02](https://user-images.githubusercontent.com/24914247/34342646-90882902-e9b6-11e7-8f32-f14da72ab9f5.jpg)
[motion.log](https://github.com/Motion-Project/motion/files/1586120/motion.log)

[motion.conf.txt](https://github.com/Motion-Project/motion/files/1586122/motion.conf.txt)

**Comment by Mr-Dave** [comment]
I am pretty sure it is working since my cameras and all my testing uses it.  But in order to see it on your setup, you'd need to make a small edit and compile from source :(  

Upon reviewing that section of code I observed that the message is identical between whether it is assigning UDP or TCP.  This [line](https://github.com/Motion-Project/motion/blob/35cd0b37acf289a8bedc033fbfc51cc6dd858aca/netcam_rtsp.c#L639) needs to indicate UDP in order for it to be seen in the log.  The lines immediately above that one is where the transport gets set to TCP.

As of right now, I've marked this as a bug by virtue of the message being incorrect.

**Comment by cantonfe** [comment]
Thanks for the quick answer. I will open a new Issue. I have the same version of motion on my ubuntu computer with identical config file and everything seems to be fine (same camera). On the raspberry (raspbian) I have the image quality issue and some more (recording an event with no actual movement on it and ignoring the  event_gap 60 option).
