### ISSUE TITLE
Online documentation doesn't work

### ISSUE THREAD

**Issue by timdonovanuk** [Motion-Project/motion#607]
Quite a simple one... on the following page only the first two links work: https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html

**Comment by Mr-Dave** [comment]
I will have to contemplate how to address this one since my knowledge of html coding is limited.  

The reference that you have pointed to is the guide from the git source code which is not an official release.  Navigating from the [home page](https://motion-project.github.io/) and reviewing the latest stable release [documentation](https://motion-project.github.io/motion_guide.html) all fine.

**Comment by tosiara** [comment]
@timdonovanuk can you provide more details about what doesn't work for you? All the links in your mentioned url are working fine for me

**Comment by tosiara** [comment]
I think the problem is that Github's HTML preview is modifying HTML at runtime and injects the following tag:
```
<base href="https://raw.githubusercontent.com/Motion-Project/motion/master/motion_guide.html">
```
Which in fact changes the link structure and may break all the things. So please only use HTML preview service to only preview a singe page. Do not expect links to work in the modified version

**Comment by timdonovanuk** [comment]
I just wanted to RTFM ¯\\_(ツ)_/¯ Not really a weird request for a project.

> All the links in your mentioned url are working fine for me

So https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#The_Config_Files works for you? Because all that does is show the same page as https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html

So anyone that is new to Motion will also face the same problem of being unable to read the docs.

**Comment by tosiara** [comment]
So the problem was https://github.com/Motion-Project/motion/blob/7637a3dcd0cf694bc6b9daae4fea341d4ced1a5f/README.md containing a wrong link to online doc?

**Comment by Mr-Dave** [comment]
An additional note for clarity.  

The htmlpreview seems to be cache'ing our site and not updating with current content at least for some of us.  Starting at the `README` page and opening the motion_guide.html, it illustrates the link above which has `motion_guide.html#The_Config_Files`.  However actually looking at the source file line [here](https://github.com/Motion-Project/motion/blob/master/motion_guide.html#L31) you can see that it references `motion_config.html#The_Config_Files`

I think the following is needed:
1.  Revise the readme to point to the home page.
2.  Hard code in the home page site to some of the links to allow for escaping from htmlpreview and getting back to the home page.
3.  An additional review of all the pages to minimize the references to htmlpreview.

**Comment by Mr-Dave** [comment]
@timdonovanuk See if it is better now.

**Comment by timdonovanuk** [comment]
Working perfectly now, thank you @Mr-Dave !

**Comment by Mr-Dave** [comment]
Please enjoy Reading The Fine Manual
