### ISSUE TITLE
OGG support?

### ISSUE THREAD

**Issue by mckea** [Motion-Project/motion#616]
0. Reviewed guide and contributing documents? (Yes/No): yes
1. version [x.y.z, hash, other]:  4.0
2. installed as a package or compiled from sources [deb, rpm, git, other]: deb
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: v4l
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: debian 9

I have a custom web app to view motion video files, working fine with motion 3.3 on a Fedora system.
I've tried installing the same web app with motion 4.0 on a debian box and notice that OGG is no longer supported, which breaks my web app.

Is there some reason OGG support was removed?

Thanks!

**Comment by Mr-Dave** [comment]
From memory, the OGG was removed because:
-- It was listed as testing (aka experimental)
-- It did not playback correctly at all fps rates(it would work for some but not others)
-- The fixes for all the other containers did not work in fixing ogg.
-- Focus development efforts on correcting playback for the other containers.

**Comment by tosiara** [comment]
You can still use extpipe to produce OGG videos
