### ISSUE TITLE
Possible future capability, output track like metadata as csv file.

### ISSUE THREAD

**Issue by apiszcz** [Motion-Project/motion#632]
The object center is known to draw the cross, and bounding region is known.  It seems possible to create a mode where the following could be written as a csv file in the case of a video file and perhaps picture mode.

csv_output on|off
csv_filename (....)

(use the same base level folder currently used, use the same path setup for these files a movie, picture, timelapse)

output.csv
cameraid,,epochtime,frame,x,y,w,h,(perhaps other user configured parameters)

**Comment by Mr-Dave** [comment]
The generic move script implementation in #643 will be implemented shortly.  The functionality requested in this issue should be able to be addressed by that PR(once merged).  If there is other functionality required, additional details on the scenario will be needed.   Otherwise, I'll close this once #643 is merged.
