### ISSUE TITLE
RTSP IP Camera - Unable to open video device

### ISSUE THREAD

**Issue by bobbydriver** [Motion-Project/motion#676]
Running
motionEye Version 0.38.1 
Motion Version 4.1.1 
OS Version motionEyeOS 20180224 
Raspberry Pi 3  - Linux meye-9eadbcf6 4.9.41-v7

I have a Chinese IP camera that I'm trying to add into MotionEye. 
I located the RTSP stream using packet capture and I can open it with no issues in VLC using the URL
rtsp://192.168.0.33/onvif1

However - when I try to add it into MotionEye as a network camera it recognises the camera but will not display and shows a grey box with "Unable to open video device since.."

Calin at MotionEye suggests in these instances to raise an issue on the Motion project

Attached is the TCP trace of the stream opening OK in VLC
motion.log
motion.conf
motioneye.conf
thread-1.conf

[VLC-OK-TCP Stream.txt](https://github.com/Motion-Project/motion/files/1819176/VLC-OK-TCP.Stream.txt)
[motion.log](https://github.com/Motion-Project/motion/files/1819175/motion.log)
[motion.conf](https://github.com/Motion-Project/motion/files/1819181/motion.txt)
[motioneye.conf](https://github.com/Motion-Project/motion/files/1819182/motioneye.txt)
[thread-1.conf](https://github.com/Motion-Project/motion/files/1819183/thread-1.txt)

Any help appreciated

**Comment by Mr-Dave** [comment]
It is actually better to first ask the mailing list rather than posting a issue here on github which I try to keep to discussing code items.  Hence the first item in our contributing template of `Reviewed guide and contributing documents? (Yes/No): `

The camera url should be validated with ffplay or ffmpeg.  VLC may be able to handle the onvif1 format whereas ffplay / ffmpeg may not.  Motion uses the ffmpeg libs and the logs show ffmpeg complaining a lot about the stream contents so you may want to find the direct URL rather than the onvif1.  (Perhaps the one cited in the vlc log?).

**Comment by bobbydriver** [comment]
Sorry - I'll investigate as suggested and go via the mailing list.
What's really odd is that I left the "unable to open video device" grey box running for 5 minutes and then suddenly the stream appeared!?
If I make any changes and restart the daemon, it does the same - "unable to open" then after 5 mins it appears. Then the  stream seems to display OK for a while but occasionally drops out and then reconnects after 5 mins. 
You can close this issue tracker now -Thanks

**Comment by Mr-Dave** [comment]
With the new information, I would say that it is no longer a URL issue.  It is a issue with your local network,  Motion needs a really good connection to the camera so that it can compare one image to the next and detect motion.  VLC and ffplay may be able to use a different network protocol that allows those applications to start immediately and handle poor connections.  (They are just displaying the images to users, not processing and comparing one image to the next)
