### ISSUE TITLE
Manage step motors with RPI

### ISSUE THREAD

**Issue by AF340** [Motion-Project/motion#690]
Hello,
I'm using step motors to drive home made pi camera.
These step motors are plugged to gpio, and i'm using for the moment a flask server to pan/tilt them.
Will be great to hook the action pan/tilt from motion, calling a python script for example with the api "Track Commands":
http://motionhost.mydomain.tld/track/set?pan=10&tilt=5 event will be enough for me.
(plus sethome and gethome command) 
(port are unusefull for me)

Thanks

**Comment by Mr-Dave** [comment]
Wouldn't it work to just use the [track_generic_move](https://rawgit.com/Motion-Project/motion/master/motion_config.html#track_generic_move)?

**Comment by AF340** [comment]
Great! but i don't see any integration doc: where can i specify the script path to call? how to trigger this action? does it work with the api? 
Thanks

**Comment by AF340** [comment]
Finally, i've installed the current 'debug' version and reach to call the sh file as example.
But environment variables 'TRACK_ACTION' etc are not set since case instr is never reached
Any idea?
Thanks

**Comment by AF340** [comment]
Using my python script directly, it works.(no idea why the bash not)
I notice: 
- moving to dx/dy to 15 15 is splitted into 2 moves, 15 0 and 0 15, will be great to keep both values (my moves are asynch)
- Center always return TRACK_XOFF TRACK_YOFF to 0 0, i expect -sum(dx) -sum(dy)?
- Sethome button will be great (reset X/Y dx/dy pos)
- Speed info is missing for generic.

The new UI is great, if the above improvements are done, i'll implement a version with motion instead of flask.

Thanks

**Comment by Mr-Dave** [comment]
1.  I think we can combine the moves.  As indicated in the code comments, this was best effort on the webui changes for tracking.  It appears in the code that moving in two calls is only done when requested via the webui.  When running in regular mode, it appears that a move will execute as a single call.  

2.  I think the `TRACK_XOFF` and `TRACK_YOFF` are supposed to be offsets from the center and that the camera is assumed to have its own command for returning to center.  This is what was observed in the code for the other camera types.  The challenge is that Motion is not keeping track of where the camera is pointed.  It may have issued a command to move 15,15 but it never knows whether it actually occurred.  A subsequent call could then indicate to move 5,5.  Now to get back to center is it a move of -20,-20? -5,-5?, -15,-15?, -5,-15?, etc.   If we just assume that everything always works, there would seem to be high probability that the camera will be pointing at the sky or concrete after some time of operation. 

3.  Similar situation to 2 above.

4.  I am not clear on the `speed` question since this is an option that was designated for the stepper tracking camera.

**Comment by AF340** [comment]
1. I don't know what is the regular mode but i test using:
curl "http://ip:port/0/track/set?pan=18&tilt=12" and the move is splitted into 18/0 and 0/12

2. From my flask server, i store all the moves from the sethome action, means all sum dx/dy.
To go back to home, i call -sum(dx)/-sum(dy) from home pos.
The script to move the step motors is called each time on the fly, i cannot store the cumulative moves, that's why i used a flask server, since it's easier to keep in memory all the moves.
Each time sethome is called, all the previous moves are cleared (the variable dx/dy from the previous sethome call).

3. Sethome clears all dx/dy values from previous sethome.
I agree the server is not aware of the physical limits of the step motors, ideally, home action should first calibrate X/Y axis to move to the real center pos, and new sethome should be computed based on this real center pos.(whatever the moves, the server should know exactly the absolute pos from the center pos to detect axis limit).
Without endstops, a first approach to calibrate the limit could be movement to left/right/up/down and check motion result picture, when the pic is the same than the previous, the limit is reached?

4. I do use step motors, i've developped an high level api to move them, for the moment i set a fixed value for the speed.
