### ISSUE TITLE
WiFi issues

### ISSUE THREAD

**Issue by kgoerbig** [Motion-Project/motion#745]
I've configured wpa_supplicant.conf, however no matter what I do with it, I cannot get WiFi to work.

config:
ctrl_interface_group=0
ap_scan=1
update_config=1

network={
        mode=0
        priority=1
        scan_ssid=1
        proto=WPA2
        key_mgmt=WPA-PSK
        pairwise=TKIP
        ssid="motionpi"
        psk= "mypw"

My openwrt has a 5Ghz band encryption of psk2+ccmp. The PI sees the WiFi dongle fine, but does not get an IP. I should be able to get an IP for both the eth0 and wlan0 at the same time, correct? should there be different options in the config for wpa2 (psk2)?

What are the possibilities of getting a spot in the admin web login to configure dongles? 

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:e0:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by ccrisan** [comment]
@kgoerbig I believe you meant to open an issue on [motionEyeOS](https://github.com/ccrisan/motioneyeos) rather than motion.

If that's the case, please make sure your wifi setup works well with Raspbian first. If it doesn't, you're out of luck. If it does, get back to us by opening a motionEyeOS issue.
