### ISSUE TITLE
segmentation fault using v4l2loopback device

### ISSUE THREAD

**Issue by wgprojects** [Motion-Project/motion#746]
0. Reviewed guide and contributing documents? (Yes/No): **Yes**
1. version [x.y.z, hash, other]: **43b9c2b (master as of 20180702)**
2. installed as a package or compiled from sources [deb, rpm, git, other]: **git**
3. standalone or part of third party [motion, MotionEyeOS, other]: **standalone**
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: **v4l2 and mmal**
5. hardware [x86, ARM, other]: **Raspberry Pi / ARM**
6. operating system [16.04, Stretch, etc, FreeBSD, other]: **Raspbian Jessie 4.9.35-v7+ #1014**

[Log Gist](https://gist.github.com/wgprojects/71dead598df7e9864d8e8d099d75cc1d) including gdb backtrace (seems borked)
**Camera 1 - v4l2** loopback - Lepton thermal camera
  -on /dev/video0
  -RGB3 is the correct palette.
  -mplayer has no issue playing this device
**Camera 2 - MMAL** raspi cam 

Expected result: Both cameras stream correctly.
Actual result: 
-Camera 2 streams correctly
-Camera 1 - attempting to stream (visit URL) causes segfault.

mplayer and VLC can stream this device no problems.
Previous versions of motion have streamed this v4l2 source without segfault.
This kind of worked: [https://github.com/lowflyerUK/motion on mmal-test branch](https://github.com/lowflyerUK/motion), though the colours were messed up, which is why I tried building master.

I'm happy to do some legwork in debugging this, but hoping for a pointer in the right direction since the stack seems to be borked according to gdb. 

I've tried using avconv (Debian's ffmpeg) to display [static files ](https://motion-project.github.io/motion_config.html#Basic_Setup_Static)  but avconv can't encode for v4l2, and I am having a hard time getting ffmpeg running on Jessie.

**Comment by Mr-Dave** [comment]
Can you try the v4l2 via netcam option.  It is described in the guide [here](https://rawgit.com/Motion-Project/motion/master/motion_config.html#netcam_url)

**Comment by Mr-Dave** [comment]
The problem is the dimensions sent by the camera. You specified the dimensions of 640x480 which is fine but that was not available from the camera so it chose the closest size of 640x555 which isn't valid for Motion since height and width both need to be a multiple of 8.  

From memory, I thought the previous result in this situation was just to "give up" and say can not open device so I'm a bit surprised any previous version worked with these dimensions.

**Comment by wgprojects** [comment]
Indeed the dimensions%8 is the issue. Expanding the source image makes it stream exactly as the previous version I had working. Thanks so much for that!
I tried the netcam thing after this, but it didn't work:
[gist with netcam v4l2:///dev/video0 - Failed to open video device](https://gist.github.com/wgprojects/3a2f07ce9204da5dcee5a473e330744f)

Would you prefer if I open a new issue regarding the colour palette? 
Red appears Blue, Green -> Orange, Blue -> Green
I would have suspected BGR vs RGB or something, but Orange?
Source bytes go RGBRGB etc which is RGB3, which is the palette selected.
[gist with /dev/video0 - Working, with wrong colours](https://gist.github.com/wgprojects/c2fb52d7cf03c50ce0c9b07f90ba6b3d)

**Comment by Mr-Dave** [comment]
I will add it in under #740 and just have that issue include all the pixel format issues.  

With respect to the v4l2 via netcam, the option was not specified correctly. it would be `netcam_url v4l2:///dev/video0` not `videodevice v4l2:///dev/video0`.  This option is probably going to yield the best picture colors since it will use the ffmpeg libraries to do the color  space conversions.
