### ISSUE TITLE
Enhancement:  Allow user specified timeout parameters

### ISSUE THREAD

**Issue by eliassun** [Motion-Project/motion#793]
0. Reviewed guide and contributing documents? (Yes/No):Yes
1. version [x.y.z, hash, other]: Master branch git commit 0572a64ba90e01b6b33d8d1f7d53b9e64da6ce61
2. installed as a package or compiled from sources [deb, rpm, git, other]: git
3. standalone or part of third party [motion, MotionEyeOS, other]: motion
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: rtmp
5. hardware [x86, ARM, other]: X86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Linux motion 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

The full log is at https://drive.google.com/file/d/1suYtiee4_fz0hdxfy00liRHxdxctRbOw/view?usp=sharing

Motion server quit with the error "motion_watchdog: Thread 7 - Watchdog timeout did NOT restart, killing it!"

**Comment by Mr-Dave** [comment]
It does not appear that any of the cameras ever connected which implies a invalid URL was specified which deadlocked Motion.  I would recommend that you check that the URL specified in the motion.conf / camera.conf files work with the ffplay application.  You should also determine whether the camera has a rtsp rather than a rtmp url and use that instead as rtsp is the usual protocol.

**Comment by eliassun** [comment]
Hi Dave,
  Yes, I configured 10 camera, but only one was on line.
    I go back 4.1. So far, it is still working after more than 1 days past.
    This bug may be new after 4.1.

Thanks,
Elias

**Comment by Mr-Dave** [comment]
Hmmm.  That is actually more concerning.  There are no bugs reported for anything like this so the next release will have it.   Is there a log available that shows the results when all cameras are online?  Or perhaps describe the "bug" better with expected and actual results?  From the attached log, I can not determine what you expected to work but it didn't

**Comment by eliassun** [comment]
Here are what I am trying to do.
1. I do not have 10 cameras at hand now. I only have two cameras so far.
2. I plan to install 10 cameras in total. So, I configured 10 cameras in the motion server at one time.
3. I enabled 1 camera first for the whole night. It was working well for many hours. The motion detection was working well too. 
4. The camera may reconnect automatically time to time.
The result is it is stopped after many hours. I reproduced it every time after the motion server worked for hours.
I expect it works well for this case. V4.1 seems fine so far. But the master branch seems to have the issue. Both 4.1 and the master branch are compiled with the source code.
I do not have 10 cameras. But I can try to keep 1 camera with the master branch to see if it will happen.

**Comment by Mr-Dave** [comment]
Any update? 

And for my own clarification:  
The issue is that when you connect one camera, it works for a few hours then it disconnects.  And under 4.1, Motion is able to recover from the disconnect and connect again but under the current master it triggers a watchdog timeout.

If I have the issue correct, if you can post a log at the INF level it would be extremely helpful.

**Comment by Mr-Dave** [comment]
It took me a moment to recognize it, but the version that created the second log is not b8aa3819fa02271fda1ee3a3a75579c3036a6e86 .  It is a version from many months ago.  Look for the version number from Motion being reported and 'webu_' function calls at the start.  

Now even with the b8aa3819fa02271fda1ee3a3a75579c3036a6e86 version, there may be an issue with Motion processing multiple RTMP streams from the same camera.  It did not crash or watchdog on me, but it did go into a reconnecting loop when specifying the same camera in multiple threads.  I don't have one of those cameras so I was emulating RTMP and right now I do not know if it is just associated with the emulator.  (RTSP is really the preferred 'protocol' if available instead of RTMP.)

I'll look into the multiple streams on a single camera.  I'll also be curious to know your results with the b8aa3819fa02271fda1ee3a3a75579c3036a6e86 version since you have an actual camera that provides RTMP.  

One additional note is that many cameras have a maximum on the number of connections that they will accept.  I have 6 cameras running on Motion at ~3% cpu but can not connect 6 threads to the same camera.  The camera will just start rejecting connections.

**Comment by eliassun** [comment]
No, my camera only has one connection to the motion.  Then a viewer may connect the camera to watch what is happening time to time. I mean the max connections to the cameras are up to 2. Actually, I think it is one connection since I am using the RTMP server as the bridge. The motion server is connected to my RTMP server.

My RTMP server is sitting on the Internet. If I use RTSP, I am not sure how it can connect to my camera in my private network directly. 

I have a regular RTMP Camera and the RTMP App installed on iPhone, let me know if you really an RTMP camera to debug it. I can point my Camera to your motion server. But I need your private e-mail to give the URL that motion can pull the video.

Let me know if you still need me to run the testing or something.

**Comment by Mr-Dave** [comment]
I would still recommend using the latest git version if you need to have Motion process 10 different RTMP cameras and you hit a watchdog timeout or segfault.  

I was able to reconfigure my RTMP emulator and successfully set up Motion to watch that stream on 12 separate camera threads.  So from what I can test/see, Motion is not watchdog'ing or faulting with the RTMP.  

If you click on my name, the profile in github will show my direct email address.  I can try setting up 10 camera threads against your RTMP server and see where it is hanging.  (Assuming the configuration is Camera->RTMP Server->Motion with 10 camera files)

**Comment by eliassun** [comment]
yes, I will provide you an RTMP url to you this Thursday. 
My setup is to configure 10 cameras, but only connect 1 camera.

**Comment by eliassun** [comment]
Thanks! Dave. I will try these options.
