### ISSUE TITLE
autostart script Centos 7 

### ISSUE THREAD

**Issue by pruwait** [Motion-Project/motion#863]
# service motion start
Starting motion detection : motion
/etc/init.d/motion: line 23: start-stop-daemon: command not found
Centos 7 have't start-stop-daemon. Can some-body edit script motion.init-Debian to motion.init-Centos?

**Comment by tosiara** [comment]
Either provide more info as required by contribution guide, or this issue will be closed as Invalid
https://github.com/Motion-Project/motion/blob/master/CONTRIBUTING.md

**Comment by Mr-Dave** [comment]
I believe Centos 7 would be using `systemd` and therefore this issue is not valid because it should not use a motion.init-centos.  If you wish to add to the [motion guide](https://motion-project.github.io/motion_guide.html) providing detail for Centos, please submit a pull request with the proposed change.
