### ISSUE TITLE
RFE: failover cameras

### ISSUE THREAD

**Issue by brianjmurrell** [Motion-Project/motion#874]
0. Reviewed guide and contributing documents? (Yes/No): Yes
1. version [x.y.z, hash, other]: 4.2.1
2. installed as a package or compiled from sources [deb, rpm, git, other]: From an RPM I built from source
3. standalone or part of third party [motion, MotionEyeOS, other]: standalone
4. video stream source [V4L (card or USB), net cam (mjpeg, rtsp, other), mmal]: net cam
5. hardware [x86, ARM, other]: x86
6. operating system [16.04, Stretch, etc, FreeBSD, other]: Linux

It would be nice to be able to configure multiple cameras in a failover configuration where camera 2 is only used if camera 1 goes AWOL.

**Comment by Mr-Dave** [comment]
Wouldn't it just be `on_camera_lost` execute script to un-pause camera 2 via the webcontrol and then a additional script for `on_camera_found` to pause camera 2?

**Comment by brianjmurrell** [comment]
I suppose.  If I could get the webcontrol to work.

Is this [API documentation](https://www.lavrsen.dk/foswiki/bin/view/Motion/MotionHttpAPI) accurate?  [http://server:8082/1 on my installation](https://www.lavrsen.dk/foswiki/bin/view/Motion/MotionHttpAPI#URL_with_only_thread_number) for example returns:

```
Bad Request

The server did not understand your request.
```

I do have two cameras defined and have:

```
webcontrol_port 8082    
```

**Comment by Mr-Dave** [comment]
The project moved to github a few years ago so that link is not applicable.  The [Motion project home  page](https://motion-project.github.io/) would be a better starting point.  

The [Basic setup](https://motion-project.github.io/motion_config.html#top) provides a few things to get it working and the options list related to [webconcontrol](https://motion-project.github.io/motion_config.html#OptTopic_Webcontrol) as well as a a general [overview](https://motion-project.github.io/motion_config.html#OptDetail_Webcontrol) of it with examples are in there.
