### ISSUE TITLE
RTSP Stop Working after WEB Control.

### ISSUE THREAD

**Issue by Lu-Fi** [Motion-Project/motion#883]
I tried latest GIT Version with motioneye on Ubuntu 18.04 Server.
As Video Source i use: 1 raspberry zero w, 1 maginon IPC 100HD (MJPG) and one China Cam which is providing RTSP Streams.
Everything works if no Working Schedule is Configured in Motioneye.
If a working Schedule is configured, motioneye will enable / disable Motion Detection Dynamically on Startup / Schedule Time.
After testing this i found that RTSP Video Source stop working if status of motion detection is changed by using webcontrols.
Motion eye only sets Motion Detection on/off using motion webcontrol for schedule features.

https://github.com/ccrisan/motioneye/blob/8d718c31387c6d9cdda2ef1358ebb05d075f178e/motioneye/motionctl.py#L247

**Comment by tosiara** [comment]
Can you reproduce the issue with motion standalone?

**Comment by Lu-Fi** [comment]
Sry, it did not help to add a sleep.
Now after i revert back to 4.1.1.1 and everything works fine again.

**Comment by Mr-DaveDev** [comment]
Instead of sleep, you could also try to reject any connections until the first image is captured.  e.g. add 
`if (webui->cnt->passflag == 0) return MHD_NO;' [here](https://github.com/Motion-Project/motion/blob/7bd179c0850115c51474caa5d6bcd4784f6b8d65/webu.c#L1257)

The legacy functionality is also still in 4.2.1 which may work.  It just isn't written into the documentation how to invoke since it would be removed in the future.
