### ISSUE TITLE
Motion Eye + ServoBlasteur

### ISSUE THREAD

**Issue by Robinson128** [Motion-Project/motion#910]
Google Translate:
Hello.
Being new in the world of raspberry pi and linux distribution, I would like to combine two project to be one: video surveillance via MotionEye and a webcam, all controlled by servomotor for the rotation of the webcam. In spite of some essays, I have the impression that ServoBlaster is not compatible with MotionEye. GPIOs are like ... to activate by MotionEye ?!
That's why you sent this message, do you know if I can control the servo motor via ServoBlaster by activating the GPIO? If so, I would like to have a track on how to do it. Thanks to you and what you did. :)

P.S: je suis sur Raspberry Pi zero W qui tourne sous Rasbian GNU/Linux 9.6 (stretch)

**Comment by tosiara** [comment]
Try to ask this question in Motioneye repo: https://github.com/ccrisan/motioneye

**Comment by Mr-Dave** [comment]
This project is for Motion rather than MotionEye which generally is "on top of" the Motion application.  Direct control of GPIO is not generally supported (see open issue in this repo).  You would need to create your own scripts and code to change the gpios.  

You can see some sample scripts to control a PTZ camera in the Motion guide for [tracking_generic_move](https://motion-project.github.io/motion_config.html#track_generic_move)
