### ISSUE TITLE
How to change streaming port ?

### ISSUE THREAD

**Issue by titithebad** [Motion-Project/motion#912]
Hello,

The default streaming port is 8765, how to change it ?

Regards

**Comment by Mr-Dave** [comment]
I believe you are in the wrong project repo.  The port that you reference of 8765 is the default port for Motioneye rather than Motion so you'll need to ask the Motioneye team this question.  If you wish to change the port associated with the underlying Motion application (this project), you would do so by revising the port number in the motion.conf file.  

Motion guide related to the control is [here](https://motion-project.github.io/motion_config.html#OptDetail_Webcontrol)
Motion guide related to the live stream is [here](https://motion-project.github.io/motion_config.html#OptDetail_Stream)
Videos illustrating the default Motion interface are [here](https://www.youtube.com/channel/UCZpOjUMnc-uO3qIyZAD_4lg)
