### ISSUE TITLE
Use netcam_highres without netcam_url

### ISSUE THREAD

**Issue by angrycoding** [Motion-Project/motion#952]
I have a camera which have some built-in motion detection thing (onvif events), would be great if there would be an option to specify netcam_highres without netcam_url, so my backend that listens to onvif event stream would emit motion events itself and let motion just record video fragment for me. I tried to solve it in many different ways, including "faking" normal stream, using static JPEG images and so on, but all of those were producing even more issues (I think most of them were related to some dependencies between normal stream FPS / BPS and the rest of recording mechanics), so that did not succeed.

**Comment by tosiara** [comment]
You can trigger motion using HTTP API - https://motion-project.github.io/motion_config.html#OptDetail_Webcontrol
Another thought, if you don't need software motion detection why don't you simply invoke ffmpeg command to record the stream?

There is mail list to ask questions like that: https://sourceforge.net/projects/motion/lists/motion-user, please use that because it has wider audience

**Comment by angrycoding** [comment]
Hi, yeah i know about triggering motion events using http api, thats exactly how im doing it when using built-in camera motion detector event stream. Why I still need motion for it? Simply because i dont want to care about the rest, general place and way of configuring provided by motion along with its recording features is already enough.
