### ISSUE TITLE
Release motion > 4.2.0 for Raspbian Buster

### ISSUE THREAD

**Issue by kfeeeeee** [Motion-Project/motion#979]
Sorry, nothing else to say about this... But would be a nice thing to have :)

**Comment by rdukes6514** [comment]
Motion 4.2.2-1 is available in https://github.com/Motion-Project/motion/releases.  It does work on Buster.

**Comment by adrienbar** [comment]
Unable to install any release armhf >= 4 on Raspbian Buster (rPi3), neither with apt, apt-get, dpkg nor gdebi due to dependencies errors:
According to the details below, ffmpeg 7:3.2.12-1 is required by motion, however on buster this version of ffmpeg is outdated and only the newer ffmpeg version 7:4.1.3-1+rpt1 can be installed. The issue : **motion installer does not accept ffmpeg 7:4.1.3-1+rpt1 to meet dependencies related to ffmpeg 7:3.2.12-1.**

Details : 
The following dependencies cannot be installed on Raspbian Buster (apt, apt-get, gedebi)
- libavcodec57 (>= 7:3.2.12) or libavcodec-extra57 (>= 7:3.2.12) 
- libavdevice57 (>= 7:3.2.12)
- libavformat57 (>= 7:3.2.12)
- libavutil55 (>= 7:3.2.12)
- libmariadbclient18 (>= 10.1.37-0+deb9u1)
- libswscale4 (>= 7:3.2.12)
- libwebpmux2 (>= 0.5.1)
The install fail even with the following (newer) packages installed (as part of ffmpeg 7:4.1.3-1+rpt1):
- libavcodec58 (7:4.1.3-1+rpt1) and libavcodec-extra58 (7:4.1.3-1+rpt1)
- libavdevice58 (7:4.1.3-1+rpt1)
- libavformat58 (7:4.1.3-1+rpt1)
- libavutil56 (7:4.1.3-1+rpt1)
- libmariadb3 (replaces libmariadbclient18)
- libswscale5 (7:4.1.3-1+rpt1)
- libwebpmux2 (0.6.1-2)

It would be nice to have a fix to enjoy the latest features of motion on Raspbian Buster :-)

**Comment by rdukes6514** [comment]
I just used:

apt-get install motion libmicrohttpd12 ffmpeg v4l-utils libmariadbclient18 libpq5 python-pip python-dev libssl-dev libcurl4-openssl-dev libjpeg-dev libz-dev

wget https://github.com/Motion-Project/motion/releases/download/release-
4.2.2/pi_stretch_motion_4.2.2-1_armhf.deb

gdebi pi_stretch_motion_4.2.2-1_armhf.deb

export PIP_NO_CACHE_DIR=false

pip install motioneye
mkdir -p /etc/motioneye
cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf
mkdir -p /var/lib/motioneye
cp /usr/local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
systemctl daemon-reload
systemctl enable motioneye
systemctl start motioneye

Rebuilt it all several times to get this to work in one fell swoop...

**Comment by koelbljp** [comment]
Having the latest versions, the installation fails because of dependencies to older versions:
sudo dpkg -i pi_stretch_motion_4.2.2-1_armhf.deb
Vormals nicht ausgewähltes Paket motion wird gewählt.
(Lese Datenbank ... 120627 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von pi_stretch_motion_4.2.2-1_armhf.deb ...
Entpacken von motion (4.2.2-1) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von motion:
 motion hängt ab von libavcodec57 (>= 7:3.2.12) | libavcodec-extra57 (>= 7:3.2.12); aber:
  Paket libavcodec57 ist nicht installiert.
  Paket libavcodec-extra57 ist nicht installiert.
 motion hängt ab von libavdevice57 (>= 7:3.2.12); aber:
  Paket libavdevice57 ist nicht installiert.
 motion hängt ab von libavformat57 (>= 7:3.2.12); aber:
  Paket libavformat57 ist nicht installiert.
 motion hängt ab von libavutil55 (>= 7:3.2.12); aber:
  Paket libavutil55 ist nicht installiert.
 motion hängt ab von libmariadbclient18 (>= 10.1.37-0+deb9u1); aber:
  Paket libmariadbclient18 ist nicht installiert.
 motion hängt ab von libmicrohttpd12 (>= 0.9.50); aber:
  Paket libmicrohttpd12 ist nicht installiert.
 motion hängt ab von libpq5; aber:
  Paket libpq5 ist nicht installiert.
 motion hängt ab von libswscale4 (>= 7:3.2.12); aber:
  Paket libswscale4 ist nicht installiert.
 motion hängt ab von libwebpmux2 (>= 0.5.1); aber:
  Paket libwebpmux2 ist nicht installiert.

Would be nice if this would work on buster with actual libraries. thx.

**Comment by cook32** [comment]
Same issue, at least maybe update dependencies ?

**Comment by Mr-DaveDev** [comment]
There should not be any dependency issues as the new buster debs were built with everything updated.  

Generally, you should not try to force install a deb from a different distribution.  This could cause lots of unforeseen issues and break many other things on your computer.  Instead, consult the Motion guide and/or instructional videos on how to create your own debs using the available script.
