### ISSUE TITLE
phase-shifted motion detection causes false alarms

### ISSUE THREAD

**Issue by hoasis2** [Motion-Project/motion#992]
(3.2.12+git20140228 on Raspbian jessie with USB Webcam)

There are false detections, while motion captures a phase-shifted picture like this:

![motion](https://user-images.githubusercontent.com/27303220/63421439-1c8fc280-c3f8-11e9-878f-0733553e5392.jpg)

phase-shifted means by my 1280x720 pixel capture:
each time, exactly 250x720 pixel from the right margin will be shifted to the left margin.

Although there is no motion at all, an event is triggered.

**Comment by gnanet** [comment]
based on my experience, I would say, the motion detection does its job well, because the amount of changed pixels, it is movement indeed.

My suggestions:
- Maybe you can check your webcam on some other (a desktop or notebook) system, if the image-shifting occurs also there.
- If you have some other Webcam, try to check if this happens with that cam too.
- I would also check the usb-connection's power level, if you have a self-powered usb-hub, you should test that too.

If you have none of the above at hand, then try to lower the recording resolution, and check if the issue may vanish if the usb-bandwith is less saturated.

Hope this helps.

**Comment by hoasis2** [comment]
Thank you gnanet for the suggestions.
